### ISSUE TITLE
lint: Configure one of our linters to check for a 100 character line length limit

### ISSUE THREAD

**Issue by imphil** [lowRISC/ibex#1027]
The title says it all ... AscentLint complains about it, but seemingly no of our other linters in Ibex cares. I'd expect there to be a verible lint option we just need to turn on.

**Comment by imphil** [comment]
See the OT configuration at https://github.com/lowRISC/opentitan/blob/master/hw/lint/tools/veriblelint/rules.vbl. We'll probably get this config for free once we vendor the latest changes in from OT.

**Comment by GregAC** [comment]
Verible lint is now running in CI
