### ISSUE TITLE
Run sanity regression in CI

### ISSUE THREAD

**Issue by imphil** [lowRISC/ibex#1079]
Blockers:
- [x] riscv-dv Python 3.5-compat: https://github.com/google/riscv-dv/pull/684. Merged in https://github.com/lowRISC/ibex/pull/1081
- [x] Determine final command to run. https://github.com/lowRISC/ibex/issues/698
- [x] Fail CI if a test fails: https://github.com/lowRISC/ibex/issues/1083

**Comment by imphil** [comment]
I now have the regression running in CI, but I get the following errors/time outs:

```
2020-08-20T17:58:58.0377875Z Thu, 20 Aug 2020 17:58:58 ERROR    Timeout[10s]: /nas/lowrisc/tools/spike-ibex/20200819-git-57023895458bc5206fe59fa229e0be6b05aa2f25/bin/spike --log-commits --isa=rv32imcb -l out/seed-1/instr_gen/asm_tests/riscv_interrupt_instr_test_0.o &> out/seed-1/instr_gen/spike_sim/riscv_interrupt_instr_test.0.log
Thu, 20 Aug 2020 18:10:22 ERROR    Timeout[300s]: env SIM_DIR=out/seed-1/rtl_sim/riscv_debug_instr_test.0   out/seed-1/rtl_sim/vcs_simv +vcs+lic+wait +signature_addr=8ffffffc  -ucli -do ./vcs.tcl       +ntb_random_seed=1 +UVM_TESTNAME=core_ibex_debug_instr_test +bin=out/seed-1/instr_gen/asm_tests/riscv_debug_instr_test_0.bin     +ibex_tracer_file_base=out/seed-1/rtl_sim/riscv_debug_instr_test.0/trace_core     -l out/seed-1/rtl_sim/riscv_debug_instr_test.0/sim.log  +require_signature_addr=1 +enable_debug_seq=1 
Thu, 20 Aug 2020 18:24:38 ERROR    Timeout[300s]: env SIM_DIR=out/seed-1/rtl_sim/riscv_interrupt_instr_test.0   out/seed-1/rtl_sim/vcs_simv +vcs+lic+wait +signature_addr=8ffffffc  -ucli -do ./vcs.tcl       +ntb_random_seed=1 +UVM_TESTNAME=core_ibex_interrupt_instr_test +bin=out/seed-1/instr_gen/asm_tests/riscv_interrupt_instr_test_0.bin     +ibex_tracer_file_base=out/seed-1/rtl_sim/riscv_interrupt_instr_test.0/trace_core     -l out/seed-1/rtl_sim/riscv_interrupt_instr_test.0/sim.log  +require_signature_addr=1 +enable_irq_single_seq=1 


2020-08-20T18:37:21.0145294Z Thu, 20 Aug 2020 18:37:21 INFO     40 PASSED, 3 FAILED
```

(I stripped out all the INFO messages.)


@udinator are those failures expected?

**Comment by udinator** [comment]
Is switching to OVPsim possible for CI runs?

RE failures in riscv_debug_instr_test and riscv_interrupt_instr_test - I haven't encountered timeouts like this yet. I'll look into them, thanks for pointing it out!

**Comment by imphil** [comment]
> Is switching to OVPsim possible for CI runs?

Yes. I'd prefer Spike since it is an open source tool, but if we have a good reason to prefer ovpsim we can use that as well.

**Comment by udinator** [comment]
I use OVPsim mainly because if I enable timer interrupts (`mie.mtie`) in Spike, Spike will start an internal watchdog timer based off of `mtimecmp` and `mtime` which will trigger timer interrupts - this creates some issues as these CSRs aren't implemented in Ibex.
I'm still investigating whether there is a way to disable this watchdog in Spike.

If you want to use Spike for CI, all you'll have to do is ensure that the `+enable_timer_irq` option is set to 0.
