### ISSUE TITLE
[RTL] Illegal Instructions occur when dummy instructions are enabled and RV32M = 0

### ISSUE THREAD

**Issue by zdogs** [lowRISC/ibex#1080]
Bug conditions:
- parameter bit               RV32M                    = 1'b0,
- parameter bit               SecureIbex              = 1'b1,
- Bit 2 of cpuctrl register (dummy_instr_en)  is set 

Description:
When a dummy instruction is executed, an illegal opcode is set when the dummy instruction opcode corresponds to a MUL or DIV.

I would recommend to remove MUL and DIV from dummy opcodes.

![illeg_instr](https://user-images.githubusercontent.com/51697819/90790308-32d0a700-e308-11ea-8109-f09dbb03e427.PNG)

**Comment by tomroberts-lowrisc** [comment]
Thanks for filing the issue. I'll look into fixing it, or updating the documentation to disallow the combination of RV32M==0 and SecureIbex==1.
