### ISSUE TITLE
[rtl] PC mismatch alarm caused by an instruction bus error

### ISSUE THREAD

**Issue by zdogs** [lowRISC/ibex#1094]
Hi,

The PC mismatch alarm fires on an instruction bus error. 

conditions: 
- parameter bit               SecureIbex               = 1'b1
-  A bus error is generated by the system, instr_err_i = 1'b1

![pc_mismartch_instr_err](https://user-images.githubusercontent.com/51697819/91044171-25236600-e615-11ea-84ee-148647e40596.PNG)

**Comment by GregAC** [comment]
Thanks for the report, I should note that the `SecureIbex` features are still under development and aren't yet fully tested so there's likely to be a few issues.
