### ISSUE TITLE
Update fetch_enable signal

### ISSUE THREAD

**Issue by tomroberts-lowrisc** [lowRISC/ibex#1105]
We have a requirement from OpenTitan to be able to block the CPU from executing at certain points. I propose we update the existing fetch_enable signal to do that, since it's current behavior is a bit confusing and probably not that useful.

**Comment by rswarbrick** [comment]
@tomroberts-lowrisc: Do we still have this requirement? (Since I think we never allow the CPU to recover after it's been squashed, presumably another way to do this on the OT side would be to gate the fetch signal in rv_core_ibex).

**Comment by tomroberts-lowrisc** [comment]
Still need to do something here - the fetch_enable_i signal currently does nothing once the core is actually running so would need to change its behaviour and document it

**Comment by rswarbrick** [comment]
Understood. What I meant is that we *could* choose just to squash outgoing fetches in `rv_core_ibex`. But, thinking about it, that probably isn't enough when there's also an icache.
