### ISSUE TITLE
RISC-V vector extension

### ISSUE THREAD

**Issue by oholimoli** [lowRISC/ibex#1123]
Are there any plans to (partially) integrate the RISC-V vector extension into Ibex?

**Comment by GregAC** [comment]
No plans at present. It should be noted Ibex is a smaller core intended more for applications seeking low area and power usage as opposed to a larger higher-performance core so the vector extension isn't a clear match for Ibex's design point.

Though it could be useful if Ibex is in a heterogeneous system for example, which has a set of cores with different power/performance trade offs. Keeping the same ISA support among all cores makes things easier for software as well as offering more flexibility. An application that wants to make heavy usage of vectors but seeks low area could also benefit from an Ibex vector implementation.

We'd need to look at the vector extension in more detail to see if a sensible implementation that fits within Ibex's design point is plausible.
