### ISSUE TITLE
Illegal Instruction Exception not Raised

### ISSUE THREAD

**Issue by shetalani** [lowRISC/ibex#1129]
**RISC-V Specification:**

> Unprivileged ISA

**Issue Description:**

An illegal instruction updates the register file and the associated csrs and executes normally without raising an illegal instruction exception.

**Example:**

The instruction 32'h2820d013 is decoded and executed with no illegal instruction exception being flagged, as machine csrs: mepc, mstatus and mcause aren't updated. 

![illegalInstr](https://user-images.githubusercontent.com/54367010/95882023-7cbe9200-0d79-11eb-97de-fd485e24e459.PNG)

---

Product: OneSpin 360 DV-Verify
App: Processor Verification App
Tool's version: 2020.2.0

**Comment by tomroberts-lowrisc** [comment]
Thanks for raising this @shetalani 
I have a proposed fix in #1130 - can you give that a go and let us know if it fixes the problem?

**Comment by shetalani** [comment]
@tomroberts-lowrisc It is fixed, my pleasure!
