### ISSUE TITLE
riscv_debug_branch_jump_test case fail

### ISSUE THREAD

**Issue by zjuwlh** [lowRISC/ibex#1139]
Hi,

when I run the riscv_debug_branch_jump_test case , the case will fail because access the unintialzed address, can anyone also find the same issue? Or can anyone help check this issue? my command is the following:
**make ISA=rv32imc ITERATIONS=1 IBEX_CONFIG=small TEST=riscv_debug_branch_jump_test SEED=29354**
can someone also help run on your side to check if there is the same issue on your side?

Thanks,
Lihua

**Comment by zjuwlh** [comment]
by the way, I use the OVPSIM as a ISA.

**Comment by tomroberts-lowrisc** [comment]
Confirmed I also see the same issue. I think there is a known problem with this test at the moment - @udinator might know?

**Comment by udinator** [comment]
Yes, there is a known issue with the test at the moment.

**Comment by zjuwlh** [comment]
Thanks for your confirm, do you have any plan when will improve the test?

**Comment by tomroberts-lowrisc** [comment]
I have a fix for the issue [here](https://github.com/google/riscv-dv/pull/734)

**Comment by zjuwlh** [comment]
Thanks.

**Comment by udinator** [comment]
This issue should now be resolved - the updates to the instruction generator have been vendored into Ibex repository.
