### ISSUE TITLE
ReadTheDocs rendering bug with Chrome

### ISSUE THREAD

**Issue by ikarageo** [lowRISC/ibex#115]
Figure 6 in https://ibex-core.readthedocs.io/en/latest/register_file.html appears minuscule in  Google Chrome 75.0.3770.100 for Windows 10.

**Comment by towoe** [comment]
Hello,
I used Chrome (same version) in Windows 10 to check the image. For me there is no problem with Figure 6. So the problem might have another cause and is not directly related to the browser and the OS?

**Comment by ikarageo** [comment]
Hi, 
Thanks for checking it. After further inspection I concluded that it is caused by a chrome extension. Normally I check things in incognito which disables all extensions, but I accidentally had this extension enabled also in incognito. Inspect element showed me the following for the `div` the image belongs to:
```
element.style {
}
injected stylesheet
#timing {
    width: 25px;
    margin: 5px;
}
...
```
This shows that the 25px width constraint was injected (by an extension).

**Comment by imphil** [comment]
Thanks for checking @ikarageo. I guess we can close this then as something we cannot do anything about it.
