### ISSUE TITLE
Unexpected behavior when OUTPUT=sim

### ISSUE THREAD

**Issue by hodjat91** [lowRISC/ibex#1158]
Hello @rswarbrick ,

Bellow command leads to a repetitive (redundant) operation because of having "sim" as the output directory (this will be fixed by simply changing the directory name to something else, say SIM). The unexpected behavior is that I think since 'sim' is the main target in the Makefile of `dv/uvm/core_ibex`, it repeats the whole process (program generation/compilation/execution) under a new random seed because it detects a change in COMPILE_OPTS. 

Command: 
`make -C dv/uvm/core_ibex/ COV=1 TIMEOUT=10000 ISA=rv32imc ISS=spike  SIMULATOR=vcs WAVES=0 TESTLIST=/path/to/testlist OUT=sim`

Console output:
make: Entering directory '/dv/uvm/core_ibex'
mkdir -p sim/seed-20667/.metadata
Fri, 30 Oct 2020 02:46:59 INFO     Creating output directory: sim/seed-20667/instr_gen
Fri, 30 Oct 2020 02:46:59 INFO     Processing regression test list : vendor/google_riscv-dv/yaml/base_testlist_single.yaml, test: riscv_rand_instr_test
Fri, 30 Oct 2020 02:46:59 INFO     Found matched tests: riscv_rand_instr_test, iterations:1
Fri, 30 Oct 2020 02:46:59 INFO     Processing simulator setup file : vendor/google_riscv-dv/yaml/simulator.yaml
Fri, 30 Oct 2020 02:46:59 INFO     Found matching simulator: vcs
Fri, 30 Oct 2020 02:46:59 INFO     Building RISC-V instruction generator
Fri, 30 Oct 2020 02:47:32 INFO     Running RISC-V instruction generator
Fri, 30 Oct 2020 02:47:32 INFO     Generating 1 riscv_rand_instr_test
Fri, 30 Oct 2020 02:47:32 INFO     Running riscv_rand_instr_test with 1 batches
Fri, 30 Oct 2020 02:47:32 INFO     Running riscv_rand_instr_test, batch 1/1, test_cnt:1
Fri, 30 Oct 2020 02:47:36 INFO     Creating output directory: sim/seed-20667/instr_gen
Fri, 30 Oct 2020 02:47:36 INFO     Processing regression test list : vendor/google_riscv-dv/yaml/base_testlist_single.yaml, test: riscv_rand_instr_test
Fri, 30 Oct 2020 02:47:36 INFO     Found matched tests: riscv_rand_instr_test, iterations:1
Fri, 30 Oct 2020 02:47:36 INFO     Compiling sim/seed-20667/instr_gen/asm_tests/riscv_rand_instr_test_0.S
Fri, 30 Oct 2020 02:47:36 INFO     Converting to sim/seed-20667/instr_gen/asm_tests/riscv_rand_instr_test_0.bin
Fri, 30 Oct 2020 02:47:36 INFO     Creating output directory: sim/seed-20667/instr_gen
Fri, 30 Oct 2020 02:47:36 INFO     Processing regression test list : vendor/google_riscv-dv/yaml/base_testlist_single.yaml, test: riscv_rand_instr_test
Fri, 30 Oct 2020 02:47:36 INFO     Found matched tests: riscv_rand_instr_test, iterations:1
Fri, 30 Oct 2020 02:47:36 INFO     Processing ISS setup file : vendor/google_riscv-dv/yaml/iss.yaml
Fri, 30 Oct 2020 02:47:36 INFO     Found matching ISS: spike
Fri, 30 Oct 2020 02:47:36 INFO     spike sim log dir: sim/seed-20667/instr_gen/spike_sim
Fri, 30 Oct 2020 02:47:36 INFO     Running spike sim: sim/seed-20667/instr_gen/asm_tests/riscv_rand_instr_test_0.o
mkdir -p sim/rtl_sim
Fri, 30 Oct 2020 02:47:36 INFO     Processing simulator setup file : yaml/rtl_simulation.yaml
Fri, 30 Oct 2020 02:47:36 INFO     Compiling TB
rm -rf sim/seed-20667/rtl_sim
cp -r sim/rtl_sim sim/seed-20667
Fri, 30 Oct 2020 02:48:02 INFO     Processing simulator setup file : yaml/rtl_simulation.yaml
Fri, 30 Oct 2020 02:48:03 INFO     Processing regression test list : vendor/google_riscv-dv/yaml/base_testlist_single.yaml, test: riscv_rand_instr_test
Fri, 30 Oct 2020 02:48:03 INFO     Found matched tests: riscv_rand_instr_test, iterations:1
Fri, 30 Oct 2020 02:48:03 INFO     Running RTL simulation...
Fri, 30 Oct 2020 02:48:03 INFO     Running core_ibex_base_test with sim/seed-20667/instr_gen/asm_tests/riscv_rand_instr_test_0.bin
Fri, 30 Oct 2020 02:48:07 INFO     Processing regression test list : vendor/google_riscv-dv/yaml/base_testlist_single.yaml, test: riscv_rand_instr_test
Fri, 30 Oct 2020 02:48:07 INFO     Found matched tests: riscv_rand_instr_test, iterations:1
Fri, 30 Oct 2020 02:48:07 INFO     Comparing spike/DUT sim result : sim/seed-20667/instr_gen/asm_tests/riscv_rand_instr_test.0.o
Fri, 30 Oct 2020 02:48:07 INFO     Processing ibex log : sim/seed-20667/rtl_sim/riscv_rand_instr_test.0/trace_core_00000000.log
Fri, 30 Oct 2020 02:48:07 INFO     Processed instruction count : 193
Fri, 30 Oct 2020 02:48:07 INFO     CSV saved to : sim/seed-20667/rtl_sim/riscv_rand_instr_test.0/trace_core_00000000.csv
Fri, 30 Oct 2020 02:48:07 INFO     Processing spike log : sim/seed-20667/instr_gen/spike_sim/riscv_rand_instr_test.0.log
Fri, 30 Oct 2020 02:48:07 INFO     Processed instruction count : 195
Fri, 30 Oct 2020 02:48:07 INFO     CSV saved to : sim/seed-20667/instr_gen/spike_sim/riscv_rand_instr_test.0.csv
Fri, 30 Oct 2020 02:48:07 INFO     1 PASSED, 0 FAILED
Fri, 30 Oct 2020 02:48:07 INFO     RTL & ISS regression report at sim/seed-20667/regr.log
Fri, 30 Oct 2020 02:48:07 INFO     Searching sim/seed-20667 for coverage database
Fri, 30 Oct 2020 02:48:07 INFO     Generating merged coverage directory
**_mkdir -p sim
Repeating compiling TB because variable COMPILE_OPTS has changed value._**
mkdir -p sim/seed-14582/.metadata
Fri, 30 Oct 2020 02:48:12 INFO     Creating output directory: sim/seed-14582/instr_gen
Fri, 30 Oct 2020 02:48:12 INFO     Processing regression test list : vendor/google_riscv-dv/yaml/base_testlist_single.yaml, test: riscv_rand_instr_test
Fri, 30 Oct 2020 02:48:12 INFO     Found matched tests: riscv_rand_instr_test, iterations:1
Fri, 30 Oct 2020 02:48:12 INFO     Processing simulator setup file : vendor/google_riscv-dv/yaml/simulator.yaml
Fri, 30 Oct 2020 02:48:12 INFO     Found matching simulator: vcs
Fri, 30 Oct 2020 02:48:12 INFO     Building RISC-V instruction generator
Fri, 30 Oct 2020 02:48:43 INFO     Running RISC-V instruction generator
Fri, 30 Oct 2020 02:48:43 INFO     Generating 1 riscv_rand_instr_test
Fri, 30 Oct 2020 02:48:43 INFO     Running riscv_rand_instr_test with 1 batches
Fri, 30 Oct 2020 02:48:43 INFO     Running riscv_rand_instr_test, batch 1/1, test_cnt:1
Fri, 30 Oct 2020 02:48:46 INFO     Creating output directory: sim/seed-14582/instr_gen
Fri, 30 Oct 2020 02:48:46 INFO     Processing regression test list : vendor/google_riscv-dv/yaml/base_testlist_single.yaml, test: riscv_rand_instr_test
Fri, 30 Oct 2020 02:48:46 INFO     Found matched tests: riscv_rand_instr_test, iterations:1
Fri, 30 Oct 2020 02:48:46 INFO     Compiling sim/seed-14582/instr_gen/asm_tests/riscv_rand_instr_test_0.S
Fri, 30 Oct 2020 02:48:46 INFO     Converting to sim/seed-14582/instr_gen/asm_tests/riscv_rand_instr_test_0.bin
Fri, 30 Oct 2020 02:48:46 INFO     Creating output directory: sim/seed-14582/instr_gen
Fri, 30 Oct 2020 02:48:46 INFO     Processing regression test list : vendor/google_riscv-dv/yaml/base_testlist_single.yaml, test: riscv_rand_instr_test
Fri, 30 Oct 2020 02:48:46 INFO     Found matched tests: riscv_rand_instr_test, iterations:1
Fri, 30 Oct 2020 02:48:46 INFO     Processing ISS setup file : vendor/google_riscv-dv/yaml/iss.yaml
Fri, 30 Oct 2020 02:48:46 INFO     Found matching ISS: spike
Fri, 30 Oct 2020 02:48:46 INFO     spike sim log dir: sim/seed-14582/instr_gen/spike_sim
Fri, 30 Oct 2020 02:48:46 INFO     Running spike sim: sim/seed-14582/instr_gen/asm_tests/riscv_rand_instr_test_0.o
Fri, 30 Oct 2020 02:48:47 INFO     Processing simulator setup file : yaml/rtl_simulation.yaml
Fri, 30 Oct 2020 02:48:47 INFO     Compiling TB
rm -rf sim/seed-14582/rtl_sim
cp -r sim/rtl_sim sim/seed-14582
Fri, 30 Oct 2020 02:49:10 INFO     Processing simulator setup file : yaml/rtl_simulation.yaml
Fri, 30 Oct 2020 02:49:10 INFO     Processing regression test list : vendor/google_riscv-dv/yaml/base_testlist_single.yaml, test: riscv_rand_instr_test
Fri, 30 Oct 2020 02:49:10 INFO     Found matched tests: riscv_rand_instr_test, iterations:1
Fri, 30 Oct 2020 02:49:10 INFO     Running RTL simulation...
Fri, 30 Oct 2020 02:49:10 INFO     Running core_ibex_base_test with sim/seed-14582/instr_gen/asm_tests/riscv_rand_instr_test_0.bin
Fri, 30 Oct 2020 02:49:15 INFO     Processing regression test list : vendor/google_riscv-dv/yaml/base_testlist_single.yaml, test: riscv_rand_instr_test
Fri, 30 Oct 2020 02:49:15 INFO     Found matched tests: riscv_rand_instr_test, iterations:1
Fri, 30 Oct 2020 02:49:15 INFO     Comparing spike/DUT sim result : sim/seed-14582/instr_gen/asm_tests/riscv_rand_instr_test.0.o
Fri, 30 Oct 2020 02:49:15 INFO     Processing ibex log : sim/seed-14582/rtl_sim/riscv_rand_instr_test.0/trace_core_00000000.log
Fri, 30 Oct 2020 02:49:15 INFO     Processed instruction count : 195
Fri, 30 Oct 2020 02:49:15 INFO     CSV saved to : sim/seed-14582/rtl_sim/riscv_rand_instr_test.0/trace_core_00000000.csv
Fri, 30 Oct 2020 02:49:15 INFO     Processing spike log : sim/seed-14582/instr_gen/spike_sim/riscv_rand_instr_test.0.log
Fri, 30 Oct 2020 02:49:15 INFO     Processed instruction count : 197
Fri, 30 Oct 2020 02:49:15 INFO     CSV saved to : sim/seed-14582/instr_gen/spike_sim/riscv_rand_instr_test.0.csv
Fri, 30 Oct 2020 02:49:15 INFO     1 PASSED, 0 FAILED
Fri, 30 Oct 2020 02:49:15 INFO     RTL & ISS regression report at sim/seed-14582/regr.log
Fri, 30 Oct 2020 02:49:15 INFO     Searching sim/seed-14582 for coverage database
Fri, 30 Oct 2020 02:49:15 INFO     Searching sim/seed-20667 for coverage database
Fri, 30 Oct 2020 02:49:15 INFO     Generating merged coverage directory
mkdir -p sim
make: Leaving directory 'dv/uvm/core_ibex'

Thanks,
Hodjat

**Comment by rswarbrick** [comment]
Thanks for the bug report, and the analysis. Even with your comments, it took me a while to understand what on earth was going on! Anyway, this should be fixed by the linked PR. If you really want an output directory called `sim` in the meantime, you could try passing `OUT=sim/` (with the trailing slash). I haven't checked, but I suspect it will work!
