### ISSUE TITLE
riscv_dret_test fail

### ISSUE THREAD

**Issue by zjuwlh** [lowRISC/ibex#1166]
Hi

When IBEX_CONFIG=small, SEED=462, ISS=ovpsim, riscv_dret_test fail, could you please help check if it is a really RTL issue?

Thanks,
Lihua

**Comment by GregAC** [comment]
I couldn't reproduce this one

**Comment by zjuwlh** [comment]
this test is pass in the latest database version, please close this issue, thanks.
