### ISSUE TITLE
cpu can't wake up after executing wfi to go into sleep mode

### ISSUE THREAD

**Issue by zjuwlh** [lowRISC/ibex#1189]
Hi ,

When running riscv_debug_instr_test, fo r some seed(SEED=16926 ITERATIONS=25), cpu will execute wfi and go into sleep during non-debug mode, in this case, if the return value of decode_instr is always 0, debug_req isn't asserted in DV test bench, the cpu will always is in sleep mode and can't wake up. does anyone also find this issue? and how to fix in test bench

**Comment by tomroberts-lowrisc** [comment]
Probably one for @udinator

**Comment by rswarbrick** [comment]
@udinator: Ping!

**Comment by udinator** [comment]
I think @GregAC has fixed this in one of his previous bug-fix PRs (#1266 I think?) - could you confirm?

**Comment by GregAC** [comment]
Yes that should have done it, so I'll close this @zjuwlh do let us know if you see a similar failure again with the fix. I haven't been seeing those failures myself in regression runs I've been doing.
