### ISSUE TITLE
Run full DV regression regularly

### ISSUE THREAD

**Issue by imphil** [lowRISC/ibex#1221]
We currently run a very limited smoke regression on every master commit/PR, but don't run the full DV regression suite. This suite takes significantly longer to run, so we need to run it in regular intervals, e.g. once a day or a week, depending on the runtime and availability of compute resources and licenses. (I had an initial look and we probably need to run it on the weekend, we're busy 24 hours otherwise.)

The current plan is to run the tests in our normal Azure Pipelines infrastructure, scheduled according to our desired interval.

Dependencies:
* [x] Choose a suitable test list for each configuration: #1220 
* [ ] Pipelines configuration: Current draft at https://github.com/lowRISC/lowrisc-private-ci/blob/ibex-regression/jobs-ibex-regression.yml
* [ ] Pass PMP tests reliably: https://github.com/lowRISC/ibex/issues/1223

**Comment by imphil** [comment]
@udinator FYI, I'll take care of the setup, I only need your input for the dependencies.

**Comment by GregAC** [comment]
We now have regular full regression runs.
