### ISSUE TITLE
misa register

### ISSUE THREAD

**Issue by eroom1966** [lowRISC/ibex#123]
Looking at the documentation here
https://ibex-core.readthedocs.io/en/latest/cs_registers.html

I cannot see a description of the MISA register regarding the enabling/disabling of MISA[C]
Assuming I have a core configured as RV32IMC
in lowRISC, is it possible to disable compressed instructions at runtime by setting MISA[C]=0

Thx
Lee

**Comment by asb** [comment]
misa is fixed at design time, so there's no support for enabling/disabling extensions dynamically.

**Comment by asb** [comment]
I've submitted PR #128 to improve the documentation. Thanks for the report!
