### ISSUE TITLE
User/Priv spec

### ISSUE THREAD

**Issue by eroom1966** [lowRISC/ibex#124]
I see that the current code conforms to PRIV 1.11, But I cannot find anywhere which indicates the USER level, I would presume 2.3, but I guess it could be 2.2. In which case where should I look I cannot find it in the docs
Thx
Lee

**Comment by imphil** [comment]
Ibex targets the latest (ratified) spec version, so that's 20190608-Base-Ratified (v2.2). (I find the versioning of the user spec highly confusing these days, with version numbers for the individual modules.)

**Comment by imphil** [comment]
TODO: Add this information to the documentation.

**Comment by imphil** [comment]
@eroom1966 does #200 answer your questions?

**Comment by eroom1966** [comment]
sorry, yes it does - thx

**Comment by imphil** [comment]
No need to be sorry, this information was/is missing from the docs and it's great that you asked for it to be included!
