### ISSUE TITLE
Not able to run hello model with rv32emc

### ISSUE THREAD

**Issue by rahulraveendran15-coder** [lowRISC/ibex#1244]
Hi,
I am trying to run hello software program with RV32EMC instruction set. On compilation of the files it is showing me the following error. How can I run hello_world  with RV32EMC architecture? It is showing error from crt0.S file

![image](https://user-images.githubusercontent.com/60182727/105354518-f542b380-5bf0-11eb-8d09-e0a1181a2882.png)

**Comment by GregAC** [comment]
The 'E' extension cuts down the number of registers to 16. crt0.S contains instructions which use registers above `x15` so won't work with the `E` extension.

We don't have any example software designed for use with the `E` extension and I'm uncertain how good the compiler support for it is. You'd need to write some and experiment for yourself.

**Comment by rswarbrick** [comment]
I'm closing this issue as I believe the question has been answered. Please re-open or file a new issue if there's something we've missed.
