### ISSUE TITLE
Hello there.

### ISSUE THREAD

**Issue by mike3s** [lowRISC/ibex#1288]
## My Environment

**EDA tool and version:**

**Operating system:**

**Version of the Ibex source code:**

**Comment by mike3s** [comment]
I am trying to setup an ibex core using Vivado 2018.3 in windows 10.
No luck yet.
Is there any walkthrough or guide?

**Comment by rswarbrick** [comment]
Hi there. Have you found our [user guide](https://ibex-core.readthedocs.io/en/latest/02_user/index.html)? You'll also probably want some form of simple SoC. We have an example for the Arty A7 development board: see the "examples" section of the user guide.

**Comment by mike3s** [comment]
For now i dont want to use any SoC. I just want to simulate the core in Vivado. I also tried the example but I faced some errors. I will try again and I will post the exact procedure I follow to check if I done something wrong.
thank you,
Mike

**Comment by rswarbrick** [comment]
Great, looking forward to hearing how things go!
