### ISSUE TITLE
VCS reported an error, NYI-CSTR-SYS-FTC

### ISSUE THREAD

**Issue by SerLippo** [lowRISC/ibex#1314]
I am totally a rookie and learning this.
I did nothing but download the toolchains and build the spike under the user guide.
When I type "make" in the terminal.
My VCS just report an error like this.

NYI-CSTR-SYS-FTC
riscv_instr_pkg, "$clog2(((XLEN * 4) / 8))"
  System function calls are not yet implemented in constraints.
  Remove the function call or if possible replace it with an integral state 
  variable assigned in pre_randomize().

## My Environment

lowrisc-toolchain-rv32imc-20200904-1.tar.xz
from
https://github.com/lowRISC/lowrisc-toolchains

spike
from
https://github.com/riscv/riscv-isa-sim

**EDA tool and version:**

VCS L-2016.06
uvm1.2

**Operating system:**

"Ubuntu Linux 20.04" 

**Version of the Ibex source code:**

latest, just download today 3.23.2021

**Comment by rswarbrick** [comment]
I suspect we just require a newer version of VCS than that. I see that we don't list a minimum version in our tool requirements page (sorry!), but we've been using the "Q-2020.03" series of releases to test things locally. I'll file a follow-up issue to track adding a version to the requirements page.

**Comment by SerLippo** [comment]
> I suspect we just require a newer version of VCS than that. I see that we don't list a minimum version in our tool requirements page (sorry!), but we've been using the "Q-2020.03" series of releases to test things locally. I'll file a follow-up issue to track adding a version to the requirements page.

thanks, I will updata my VCS and try again.
