### ISSUE TITLE
DbgTriggerEn impacts mcounteren

### ISSUE THREAD

**Issue by Silabs-ArjanB** [lowRISC/ibex#1379]
Why does DbgTriggerEn impact mcounteren? That does not look correct to me.

>       // mcounteren: machine counter enable
>       CSR_MCOUNTEREN: begin
>         csr_rdata_int = '0;
>         illegal_csr   = ~DbgTriggerEn;
>       end

**Comment by tomroberts-lowrisc** [comment]
Agreed that looks incorrect - will fix

**Comment by Silabs-ArjanB** [comment]
Thank you!
