### ISSUE TITLE
Hi, Can I verify ibex using Xilinx Vivado 2020.2(which supports UVM)?

### ISSUE THREAD

**Issue by parul-d** [lowRISC/ibex#1384]
## My Environment

**EDA tool and version:**

**Operating system:**

**Version of the Ibex source code:**

**Comment by rswarbrick** [comment]
Hi there! We don't have support for running Vivado like that, so it would be quite a lot of work. For the core_ibex verification framework (the interesting bit), there are actually two things that would need doing. Firstly, riscv-dv needs teaching how to run Vivado. Secondly, our local scripts need the same.

If you'd be interested in doing this work, we could probably help but it's probably many person-days of effort.
