### ISSUE TITLE
Instruction generation through the Risc-V generator

### ISSUE THREAD

**Issue by KinzaQamar** [lowRISC/ibex#1436]
I am currently understanding the DV environment of Ibex. I wanted to know what is the exact single point where the instructions gets generated all the way from generator to the RTL

**Comment by tomroberts-lowrisc** [comment]
Hi there! There is some information on the flow here: https://ibex-core.readthedocs.io/en/latest/03_reference/verification.html

**Comment by KinzaQamar** [comment]
One more thing I wanted to know that what sort of info/data hold by the regions in .S file
