### ISSUE TITLE
[Bug] Branch prediction on predicted branches causes bad behaviour

### ISSUE THREAD

**Issue by sam-shahrestani** [lowRISC/ibex#1462]
## Steps to reproduce the issue

Consider the following code:
```
int main(int argc, char **argv) {
    static int x = 25;
    int* x_addr = (int*)&x;
    __asm__ (
        "j skip\n\t"

        "predict_to_here:\n\t" // we shouldn't branch here but even if we do, just finish
        "j finish\n\t"
        "wfi\n\t" // this will kill things if hit

        "skip:\n\t"
        "lw t0, 0(%0)\n\t"
        "beqz t0, predict_to_here\n\t" // clearly this branch is not meant to be taken but is predicted taken
        "j finish\n\t"

        "finish:\n\t"
        "nop\n\t"
        :
        :"r" (x_addr)
        : "t0"
    );
    return 0;

}
```
We would expect the following branch pattern in general: `-> skip -> finish`
Building ibex_simple_system with the following parameters works correctly:
`fusesoc --cores-root=. run --target=sim --setup --build lowrisc:ibex:ibex_simple_system --RV32E=0 --RV32M=ibex_pkg::RV32MFast --BranchTargetALU=1 --WritebackStage=1 --BranchPredictor=0`

Building with these parameters causes the core to seemingly "lock up":
`fusesoc --cores-root=. run --target=sim --setup --build lowrisc:ibex:ibex_simple_system --RV32E=0 --RV32M=ibex_pkg::RV32MFast --BranchTargetALU=1 --WritebackStage=1 --BranchPredictor=1`

## Observed Behavior

Ibex overrides `branch_mispredict_addr` by predicting on a predicted branch. This means when a mispredict fires on `beqz t0, predict_to_here` the PC fetched next is at `wfi`.

[waves.zip](https://github.com/lowRISC/ibex/files/7384667/waves.zip)

## Expected Behavior

I honestly don't know. In the prefetch buffer configuration, there is only one `branch_mispredict_addr_q` present so there is no practical way to nest branch predictions as far as I can tell. It seems like branches should just be predicted not taken when we are already on a predicted path.

## My Environment

**Compiler:**
riscv64-unknown-elf-gcc (GCC) 8.2.0

**EDA tool and version:**

Verilator 4.210 2021-07-07 rev v4.210

**Operating system:**

Ubuntu 21.04

**Version of the Ibex source code:**

cfeef7e864926cf4d30e271a3e2aa5d95e0c141f

**Comment by sam-shahrestani** [comment]
I also see the skid buffer being used due to a stall during the `lw` with `branch_mispredict_addr` updated to that suit what's loaded into that. 

I have locally patched this by removing `branch_mispredict_addr_q` from prefetch/icache and making it an IF-ID pipeline register, while also storing `addr_next` in the skid buffer if needed (I see no way around this, you can have predicted branches in skid and also in prefetch, so you need a mispredict address for both).

I feel this is more logical since the core is depending on the branch currently in ID to be synced to `branch_mispredict_addr_q` which is currently distal and embedded in an element of IF (prefetch/icache). This also removes the need to have this register/logic around it duplicated in both the icache and prefetch buffer modules.

We're running very complex, branch heavy code on Ibex and everything seems correct with these changes. I could work to make these fit the public style if they sound good.

**Comment by sam-shahrestani** [comment]
I have an attempt shuffling the NT address calculation to ID and it certainly removes a lot of code from the IF stage: https://github.com/sam-shahrestani/ibex/commit/10faa24943d6c5912bbf394d553818162e1c202a

I'm just a tiny bit concerned about the timing performance of this compared to the previous case, but I suppose a constant adder like this might be faster than some of the other IF control signals being fed back from ID.

**Comment by GregAC** [comment]
Hi @sam-shahrestani, apologies for the delay in responding.

I think the extra adder is the way to go. Timing wise we should be fine as the instruction PC and whether or not it is compressed are straight out of flops, so the corrected branch address should appear earlier in the cycle than the rest of the control going back to the IF.

You're also right about `if_instr_valid` being broken, though I might suggest a slightly different fix:

```
assign if_instr_valid   = fetch_valid | (instr_skid_valid_q) & ~nt_branch_mispredict_i);
```

The idea being `fetch_valid` shouldn't be set if we have a mispredict either.

I haven't reviewed your commit in detail (in particular the icache aspects, hopefully @tomroberts-lowrisc can take a look as he wrote the RTL originally), but it looks good from a first pass. If you want to turn into a PR we can take it from there.
