### ISSUE TITLE
ibex boot sequence and rom code

### ISSUE THREAD

**Issue by nicolast0604** [lowRISC/ibex#1509]
I am using ibex from the opentitan.
and I am wondering if there is any information for reference about the boot sequence and rom code source code.
or how to boot from SPI.

any information is welcome. :)

## My Environment

**EDA tool and version:**

**Operating system:**

**Version of the Ibex source code:**

**Comment by rswarbrick** [comment]
This is really a system-level question: things like SPI and the rom are defined in the thing that includes Ibex, not the core itself. The right place to ask is the OpenTitan project.
