### ISSUE TITLE
Ibex Memory Extension

### ISSUE THREAD

**Issue by Mousavikia** [lowRISC/ibex#1510]
Hi I know most of my question is not about Ibex but if you can help I will be very thankful. I have a Nexys4 ddr FPGA board from digilent and I want to use its ddr2 memory with the help of Vivado MIG Ip. In digilent website [SRAM to DDR Component][1] for this board it says it's ddr has 16bit data width but after I generate the ip the data width (on my side not for ddr) is 64bit. I looked at the Zynq-7000 SoC and 7 Series Devices Memory Interface Solutions v4.2 pdf and it says that 64 comes from 2*data width(16 in my case)*nCK_PER_CLK which apparently I set this to 2 by (PHY to Controller Clock Ratio	2:1) ... What all this thing mean? Does it mean in each address (address 0,1,2 and so on) I can write 64 bit data or it means if I want address 0 and write 64 bit data it actually takes address 0,1,2,3 and then I cannot write to address 1 and should start from 4 since ddr takes 16 bit data??(I am really confused...)
Besides I want to attach this ddr2 as an external memory to Ibex core but since it has 32 bit wide memory interface, so if I have 64bit data width on my side with this MIG Ip, so I should write only to 32 lower bits and waste upper 32 bits? 
Here is the instantiation code generated by Vivado MIG, I created the Ip with the settings exactly like what [SRAM to DDR Component][1] suggested.
  mig_7series_0 u_mig_7series_0 (

    // Memory interface ports

    .ddr2_addr                      (ddr2_addr),  // output [12:0]                       ddr2_addr

    .ddr2_ba                        (ddr2_ba),  // output [2:0]                      ddr2_ba

    .ddr2_cas_n                     (ddr2_cas_n),  // output                                       ddr2_cas_n

    .ddr2_ck_n                      (ddr2_ck_n),  // output [0:0]                        ddr2_ck_n

    .ddr2_ck_p                      (ddr2_ck_p),  // output [0:0]                        ddr2_ck_p

    .ddr2_cke                       (ddr2_cke),  // output [0:0]                       ddr2_cke

    .ddr2_ras_n                     (ddr2_ras_n),  // output                                       ddr2_ras_n

    .ddr2_we_n                      (ddr2_we_n),  // output                                       ddr2_we_n

    .ddr2_dq                        (ddr2_dq),  // inout [15:0]                         ddr2_dq

    .ddr2_dqs_n                     (ddr2_dqs_n),  // inout [1:0]                        ddr2_dqs_n

    .ddr2_dqs_p                     (ddr2_dqs_p),  // inout [1:0]                        ddr2_dqs_p

    .init_calib_complete            (init_calib_complete),  // output                                       init_calib_complete

      

	.ddr2_cs_n                      (ddr2_cs_n),  // output [0:0]           ddr2_cs_n

    .ddr2_dm                        (ddr2_dm),  // output [1:0]                        ddr2_dm

    .ddr2_odt                       (ddr2_odt),  // output [0:0]                       ddr2_odt

    // Application interface ports

    .app_addr                       (app_addr),  // input [26:0]                       app_addr

    .app_cmd                        (app_cmd),  // input [2:0]                                  app_cmd

    .app_en                         (app_en),  // input                                        app_en

    .app_wdf_data                   (app_wdf_data),  // input [63:0]    app_wdf_data

    .app_wdf_end                    (app_wdf_end),  // input                                        app_wdf_end

    .app_wdf_wren                   (app_wdf_wren),  // input                                        app_wdf_wren

    .app_rd_data                    (app_rd_data),  // output [63:0]   app_rd_data

    .app_rd_data_end                (app_rd_data_end),  // output                                       app_rd_data_end

    .app_rd_data_valid              (app_rd_data_valid),  // output                                       app_rd_data_valid

    .app_rdy                        (app_rdy),  // output                                       app_rdy

    .app_wdf_rdy                    (app_wdf_rdy),  // output                                       app_wdf_rdy

    .app_sr_req                     (app_sr_req),  // input                                        app_sr_req

    .app_ref_req                    (app_ref_req),  // input                                        app_ref_req

    .app_zq_req                     (app_zq_req),  // input                                        app_zq_req

    .app_sr_active                  (app_sr_active),  // output                                       app_sr_active

    .app_ref_ack                    (app_ref_ack),  // output                                       app_ref_ack

    .app_zq_ack                     (app_zq_ack),  // output                                       app_zq_ack

    .ui_clk                         (ui_clk),  // output                                       ui_clk

    .ui_clk_sync_rst                (ui_clk_sync_rst),  // output                                       ui_clk_sync_rst

      

    .app_wdf_mask                   (app_wdf_mask),  // input [7:0]  app_wdf_mask

      

    // System Clock Ports

    .sys_clk_i                       (sys_clk_i),

    .sys_rst                        (sys_rst) // input  sys_rst

    );

  [1]: https://digilent.com/reference/learn/programmable-logic/tutorials/nexys-4-ddr-sram-to-ddr-component/start

**Comment by vogelpi** [comment]
Hi,
as you noted this question is more related to Xilinx IP cores instead of Ibex. So far, we've not been using the Xilinx MIG at lowRISC and thus can't really help you. I am thus closing the issue.
