### ISSUE TITLE
Are you planning to add floating point extension with ibex?

### ISSUE THREAD

**Issue by zeeshanrafique23** [lowRISC/ibex#1520]
I want to know that does your TODO list includes the addition of floating point unit with ibex (F, D extensions)? I have implemented that with ibex, where I used the floating point unit from PULP platform and now I want to contribute.
I verified Ibex + FPU with compliance tests as well (all tests passes).

**Comment by GregAC** [comment]
We don't have any current plans to implement a floating point unit for Ibex.

We may be open to adding to one if one were contributed, though obviously it is a large block so we'd need to take our time to review so we likely couldn't merge it soon.

If the RTL has been derived from work done by PULP there's also some questions over copyright/licensing. These shouldn't be insurmountable (especially as Ibex is derived from PULP work and contains copyrights from ETH Zurich and the University of Bologna) but must be given due consideration.
