### ISSUE TITLE
Finish functional coverage plan

### ISSUE THREAD

**Issue by rswarbrick** [lowRISC/ibex#1563]

**Comment by ctopal** [comment]
@GregAC: Sorry I can't remember what we talked about this in the meeting Tuesday. Is this one done with the commit https://github.com/lowRISC/ibex/commit/f44ae900401224c88ed671a5aad738379e3dd11a or do we have some more changes pending?

**Comment by GregAC** [comment]
I'm going through my notes to see if there's anything missing.
