### ISSUE TITLE
Implement all functional coverage points

### ISSUE THREAD

**Issue by rswarbrick** [lowRISC/ibex#1564]

**Comment by rswarbrick** [comment]
Depends on #1563.

**Comment by rswarbrick** [comment]
@GregAC has some work locally that needs pushing up.

**Comment by ctopal** [comment]
@GregAC: Is there any chance where I can look at your local changes so that I can start working on this?

**Comment by ctopal** [comment]
This is getting traced in https://github.com/lowRISC/ibex/issues/1598

**Comment by ctopal** [comment]
@johngt I'll close this one up when #1700 is merged. That one was the last remaining task after a review of implemented coverage points from Greg. More details at #1697.
