### ISSUE TITLE
[test] Add tests to mix up exceptions/interrupts/debug

### ISSUE THREAD

**Issue by rswarbrick** [lowRISC/ibex#1568]

**Comment by johngt** [comment]
With reference to https://ibex-core.readthedocs.io/en/latest/03_reference/verification.html and cosim documentation found there the point here is to create new tests that can now be covered with the cosim tool that were previously not possible.

Quick discussion with @hcallahan-lowrisc identified the following pre-cursor stages.
1. Learn about the test framework
2. Learn about the Ibex architecture
3. Learn the CI framework

@hcallahan-lowrisc to discuss with @ctopal the coverage figures that are generated by CI tools to understand if tests are covering new areas and therefore useful to include in the regression tests.

44 existing tests (grep -ir " test:" ./testlist.yaml | wc -l) in [testlist.yaml](https://github.com/johngt/ibex/blob/master/dv/uvm/core_ibex/riscv_dv_extension/testlist.yaml) but want to create new tests.
Two new subissues will be created:
1. Create a single test, with increased coverage, test that it works locally and then commit to CI regression engine. Then get PR accepted.
2. Multiple other tests that increase the test coverage.

Aim is to increase total coverage of Ibex DV to sufficient level. Will update the issue with the coverage metrics that have been agreed upon.
