### ISSUE TITLE
Get core_ibex UVM tests working with Xcelium

### ISSUE THREAD

**Issue by rswarbrick** [lowRISC/ibex#1571]

**Comment by ctopal** [comment]
I believe this one relates with some common problem that Rupert solved in an [ OTBN commit ](https://github.com/lowRISC/opentitan/commit/4b7fe88d6b46854dba3b391291dd0518e15daefc) regarding the DPI calls. I am leaving the slightly cryptic error message if it might make things easier.

@ sim_riscv_arithmetic_basic_test_0.log
```
xmsim: *E,IMPDLL: Unable to load the implicit shared object.
OSDLERROR: (null)/riscv_instr_gen_tb_top/sv/_sv_export.so: cannot open shared object file: No such file or directory or file is not valid ELFCLASS64 library..
```

@ compile.log
```
xmelab: *W,DPIEXP: DPI export function in  _sv_export.so not available.
```
