### ISSUE TITLE
Debug request causes the same instruction to be executed twice

### ISSUE THREAD

**Issue by taoliug** [lowRISC/ibex#164]
In this test, debug_req is asserted while the core is executing instruction at PC 0x8000056a. dpc is saved to the current PC value rather than the next instruction. As a result, the instruction at 0x8000056a is executed again after exiting from debug mode(dret). 

ibex log
```
             8487000            4145 8000056a 00cf9f93 slli             x31, x31, 0xc       x31=0x55508000 x31:0x9d655508
             8595000            4199 80000040 3780e06f jal              x0, 58232          
             8639000            4221 8000e3b8 7b200073 dret                                
             8683000            4243 8000056a 00cf9f93 slli             x31, x31, 0xc       x31=0x08000000 x31:0x55508000
```
![ebreak_issue](https://user-images.githubusercontent.com/34581368/61328147-46d5db00-a7cf-11e9-936b-24b943170987.png)

**Comment by taoliug** [comment]
Looks like dpc value is not shown properly on the waveform, it is 0x8000056a after entering debug mode.

**Comment by vogelpi** [comment]
Thanks @taoliug for reporting this bug. You are right, it should be the address of the next instruction that is saved when entering debug mode upon a halt request. I will fix this.
