### ISSUE TITLE
VCS issue when trying to get coverage with COV=1

### ISSUE THREAD

**Issue by lotharelvin** [lowRISC/ibex#1673]
I tried to run the following command in ibex/dv/uvm/core_ibex:
` make SIMULATOR=vcs ITERATIONS=1 COV=1 VERBOSE=1 TEST=riscv_arithmetic_basic_test`

But the terminal stops at:
`Running RTL simulation at out/run/riscv_arithmetic_basic_test.1/rtl.log`

The rtl.log shows that:

Chronologic VCS simulator copyright 1991-2021
Contains Synopsys proprietary information.
Compiler version S-2021.09-SP2_Full64; Runtime version S-2021.09-SP2_Full64;  Jun  1 14:13 2022
Feature VCSMXRunTime_Net does not exist in the license file.
Or licensed number of users already reached for VCSMXRunTime_Net.
Make sure that your SNPSLMD_LICENSE_FILE is pointing to the right file.

[Wed Jun  1 14:13:34] Queuing for License VCS-Elite-Runtime/VCSMXRuntime_Net required by ......

 HIT CTRL-C to exit

However, if I changed the COV to 0, it correrctly finishes with the PASS information.

I know it's probably not an ibex issue but I cannot figure out why the change of COV option can cause the vcs fail.

Thnaks for your help!

## My Environment

**EDA tool and version:**

VCS S-2021.09-SP2

**Operating system:**

**Version of the Ibex source code:**

**Comment by rswarbrick** [comment]
I'm sorry, I'm not sure we can help with this. My guess is that your licence server isn't set up to give out a licence to VCS when it's running with coverage enabled. We don't see this locally, so I think you'll have to sort out your EDA tool setup. Note that the RTL log includes the exact VCS command so you can probably reproduce (and tweak!) it without having to debug our Makefiles/fusesoc etc.
