### ISSUE TITLE
[dv, cosim] Add support for exceptions on first instruction of interrupt

### ISSUE THREAD

**Issue by GregAC** [lowRISC/ibex#1687]
When an interrupt occurs that causes an exception on it's first instruction co-sim break. This is a missing feature that needs implementing, see the TODO here

https://github.com/lowRISC/ibex/blob/5c49fad9a236351a884f55d44248e4f9a0f7c7e5/dv/cosim/spike_cosim.cc#L145

> estimate 8

**Comment by hcallahan-lowrisc** [comment]
Closed by #1716
