### ISSUE TITLE
MEPC is not updated with correct value for illegal JALR instruction

### ISSUE THREAD

**Issue by taoliug** [lowRISC/ibex#170]
spike log

```
core   0: 0xffffffff8000f720 (0x65d42c67) unknown
core   0: exception trap_illegal_instruction, epc 0xffffffff8000f720
core   0:           tval 0x0000000000000000
core   0: 0x000000008001d000 (0x00007119) addi    sp, sp, -128

```
0x65d42c67 is detected as illegal instruction by ibex correctly. However, seems like the core still executed the JALR instruction which causes the PC changed to some unexpected value(0x65a) and get saved to MEPC eventually.

ibex log:
```
            34443000           17123 8000f720 65d42c67 INVALID                             
            34465000           17134 0000065a xxxxxxxx lui              xx, 0xxxxxx000     
```
![screencapture-remotedesktop-corp-google-access-session-6fd70a76-592d-4962-9324-fb0b435c9f3d-2019-07-17-21_31_58](https://user-images.githubusercontent.com/34581368/61429489-5d695880-a8db-11e9-8493-ca7f5e4068aa.png)

**Comment by vogelpi** [comment]
Thanks for reporting the bug @taoliug . The problem is that the `jump_set_o` signal triggering the PC to be set to the target was set although the instruction is illegal. I have created a fix for it.
