### ISSUE TITLE
[dv, fcov] Misc coverage holes

### ISSUE THREAD

**Issue by GregAC** [lowRISC/ibex#1704]
@ctopal assigned to all of these

The following misc coverpoints are not yet being hit:

- [x] Fence.I instruction execution `InstrCategoryFenceI` bin of `cp_id_instr_category` 
- [x] WFI in UMode `cp_wfi_in_umode` 
- [x] Memory RAW hazard - `cp_mem_raw_hz`
- [x] Continue sleeping on interrupt - `cp_irq_continue_sleep` 
- [x] NMI taken - `cp_nmi_taken` 
  - I'm pretty sure this is happening so this could be a broken coverpoint, begin investigating that possibility first
- [x] Interrupt taken - `cp_interrupt_taken` 
  - I'm pretty sure this is happening so this could be a broken coverpoint, begin investigating that possibility first
- [x] `cp_interrupt_taken` holes regarding `nmi_internal` and `irq_timer` 

> estimate 8
> remaining 2022-07-22 4
> remaining 2022-07-27 2

**Comment by ctopal** [comment]
NMI taken and Interrupt taken items are fixed with #1715. We are still not seeing any interrupts related with `irq_timer` and `nmi_internal` though.

- [ ] `cp_interrupt_taken` holes regarding `nmi_internal` and `irq_timer`

**Comment by ctopal** [comment]
Oh we are actually seeing the condition happen for `cp_irq_continue_sleep` but we could not catch it because we are collecting bins on every posedge of the clock (which does not work if we are sleeping!)

**Comment by ctopal** [comment]
Second item does not happen because riscv-dv disables generating `WFI` if we are in `U` mode, claiming that combination is not supported. @GregAC Should I patch riscv-dv or create a PR in their repository?

**Comment by GregAC** [comment]
> Second item does not happen because riscv-dv disables generating WFI if we are in U mode, claiming that combination is not supported. @GregAC Should I patch riscv-dv for Ibex repository or create a PR in their repository?

Do a PR for riscv-dv. You might want a separate config knob to enable it. It's not supported in the sense that it causes an exception, but we still need to test it. It would need a suitable exception handler available in generated tests.

**Comment by ctopal** [comment]
@GregAC : Done! https://github.com/google/riscv-dv/pull/877 enables us to generate `wfi` instruction in u-mode and https://github.com/lowRISC/riscv-isa-sim/pull/9 enables us to not throw out illegal instruction wrongly in the case of encountering `wfi` while we are in u-mode

**Comment by ctopal** [comment]
`nmi_internal` related one probably needs its own issue since it will be mostly related with producing stimulus in which we test `BUS.INTEGRITY` security countermeasure. Potentially a V2S task? @GregAC, WDYT?

**Comment by ctopal** [comment]
Opened #1730 for `irq_timer` hole and `cp_wfi_in_umode`

**Comment by ctopal** [comment]
Considering `nmi_internal` hole will be tracked with #1731, I believe we are done with these!
