### ISSUE TITLE
[doc] Documentation Improvement - catch all for documentation issues

### ISSUE THREAD

**Issue by johngt** [lowRISC/ibex#1710]
Catch all for all issues where users have had a misunderstanding or we have some explicit knowledge that should be shared with the community via OT documentation (e.g. knowing that specific versions work for tools).

Note: Not making this explicitly an issue for V2 but if we have spare cycles we should look at improving the documentation.

> estimate 32

**Comment by johngt** [comment]
https://github.com/lowRISC/ibex/issues/1669 - log file might grow indefinitely if pkg_config not set up explicitly. Although the issue may be resolved, need to check that in the configuration guide that we capture common errors and highlight specific expected errors if pkg_config is not set, at least for a few issues that have been reported.

**Comment by johngt** [comment]
https://github.com/lowRISC/ibex/issues/1646 - I believe that the linked issue can be closed with an update to the documentation

**Comment by johngt** [comment]
Not specifically an Ibex DV / documentation issue, but tracking https://github.com/lowRISC/opentitan/issues/2498 as a documentation issue so that we can close that out.

**Comment by GregAC** [comment]
Shifting this out of the V2 milestone

**Comment by GregAC** [comment]
Closing this as it was only relevant to prior project tracking.
