### ISSUE TITLE
[dv,core_ibex] Instantiate Scrambling Key Interface in core_ibex DV

### ISSUE THREAD

**Issue by ctopal** [lowRISC/ibex#1728]
If we are starting to issue `FENCE.I` instructions, we definitely need to drive scrambling key ports so that ICache would have a valid key. Currently we don't have a valid key, so we are stuck at an invalidating state.

>estimate 4
>remaining 2022-07-27 2

**Comment by ctopal** [comment]
This also causes any `wfi` instruction to not work essentially because we are in a constant state of waiting for a scrambling key.

**Comment by GregAC** [comment]
@ctopal please add an estimate for the overall work for this (including any work you've already done, this is so we get a more accurate picture of work completed and work remaining).
