### ISSUE TITLE
[dv,cosim] Implement internal interrupts in co-sim

### ISSUE THREAD

**Issue by GregAC** [lowRISC/ibex#1732]
Add support to cosim for internal interrupts (documented at https://ibex-core.readthedocs.io/en/latest/03_reference/exception_interrupts.html#internal-interrupts)

> estimate 8
> remaining 2022-10-06 4
> remaining 2022-10-14 2
> remaining 2022-11-01 1

**Comment by ctopal** [comment]
>remaining 2022-10-14 2

**Comment by GregAC** [comment]
@GregAC to add write suppression on ECC failures on load to co-sim environment

**Comment by GregAC** [comment]
I have a set of commits on top of Canberk's work in https://github.com/lowRISC/ibex/pull/1811 but no PR yet. Once that is merged this will be complete.

**Comment by GregAC** [comment]
Completed by https://github.com/lowRISC/ibex/pull/1907
