### ISSUE TITLE
[dv] Verify PC integrity check

### ISSUE THREAD

**Issue by GregAC** [lowRISC/ibex#1755]
Verify the PC Integrity checking countermeasure. This will involve corrupting the PC and checking the appropriate alert occurs. Ideally we will not disable the co-simulation checking around this which should be feasible as we shouldn't be retiring any instructions that involve the corrupted PC.

Write a testbench component to corrupt the PC and employ it within a suitable test.

> estimate 8
> remaining 2022-10-14 2

**Comment by andreaskurth** [comment]
Closing as completed in #1873.
