### ISSUE TITLE
[dv] Verify fetch enable

### ISSUE THREAD

**Issue by GregAC** [lowRISC/ibex#1758]
Verify the fetch enable signal. Write a sequence that can toggle it for the new sequence library. Use this sequence to randomly toggle fetch enable in some tests. It should have no impact on architectural execution (i.e. timing of instructions will differ but co-simulation checking should not find any issues).

Add a new checker that ensures that when fetch is disabled Ibex isn't fetching and executing new instructions (assertions may be sufficient)

easier tasks that anticipated (sequence is already done) so dropping estimate to 2
old estimate: 4
> estimate 2

**Comment by ctopal** [comment]
@GregAC Please go ahead I'm still working on the debug side unfortunately..

**Comment by GregAC** [comment]
Fetch enable testing added via this PR https://github.com/lowRISC/ibex/pull/1844
