### ISSUE TITLE
[dv] Verify double fault behaviour

### ISSUE THREAD

**Issue by GregAC** [lowRISC/ibex#1760]
Ibex has a double fault detector. A checker should be created to ensure this functions correctly and double faults should be stimulated in some tests.

Various work has been happening in this area, as a result this issue is less effort than originally estimated.
old estimate: 4
> estimate 2
> remaining 2022-11-8 1

**Comment by GregAC** [comment]
Added an estimate to this. The cosim side of things is handled by https://github.com/lowRISC/ibex/pull/1808 what remains is

- Produce a double fault in some test (either a new dedicated one or add them to some existing test that already generates exceptions). A read of `cpuctrlsts` that will see the `double_fault_seen` bit being set should be included. The ideal test would clear this bit, recover from the double fault and continue (some of time, other times some loop of faulting that times out would be good).
- A checker for the `double_fault_seen_o` output. This could be done as an assertion along with some tracking logic.

**Comment by johngt** [comment]
Taking @marnovandermaas off this task assignment for now.

**Comment by GregAC** [comment]
@GregAC to provide more detailed guidance on checking here

**Comment by GregAC** [comment]
Reassigning to @GregAC I should be able to address this rapidly freeing @hcallahan-lowrisc for other tasks

**Comment by GregAC** [comment]
PR https://github.com/lowRISC/ibex/pull/1916/files to add the double fault checker

**Comment by GregAC** [comment]
Closed by https://github.com/lowRISC/ibex/pull/1916
