### ISSUE TITLE
[dv] Security Feature Coverage

### ISSUE THREAD

**Issue by GregAC** [lowRISC/ibex#1762]
Document and add coverage points then ensure they're getting hit for:

- [x] Data independent timing enabled  whilst executing all instruction categories - Estimate 2
- [x] Random instruction generation
  - [x] enabled whilst executing all instruction categories  - Estimate 2
  - [x] Random instruction generated, for all possible kinds of random instruction - Estimate 2
  - [x] Cross of different generator configurations  - Estimate 2
- [x] Various faults seen - Estimate 2
  - [x] Register File ECC fault seen
  - [x] Register File write enable glitch fault seen 
  - [x] Lockstep glitch fault seen
  - [x] Icache ECC Fault seen

original estimate: 10
> estimate 4
> remaining 2022-11-01 2

**Comment by johngt** [comment]
Per discussion in internal HW meeting, Canberk going to work (with Andreas) on this. Priority on this over CSRNG V2 items as Ibex V2S scheduled for next week. If it is going to take substantial effort, then Canberk to message @GregAC given that CSRNG also needs substantial time based on initial scoping work.

**Comment by ctopal** [comment]
>remaining 2022-11-01 2
