### ISSUE TITLE
[dv] Investigate issues in mixed interrupts/traps/debug tests

### ISSUE THREAD

**Issue by GregAC** [lowRISC/ibex#1765]
> estimate 16
> remaining 2022-09-28 8

**Comment by ctopal** [comment]
>remaining 2022-28-09 8

**Comment by johngt** [comment]
@GregAC - Think that @ctopal and @hcallahan-lowrisc will need some guidance on the efforts required for this + https://github.com/lowRISC/ibex/issues/1686

**Comment by GregAC** [comment]
This test is seeing some passes, failures are generally intricate co-sim mismatch bugs (but not RTL bugs) which take significant time to resolve so moving this to V3

**Comment by GregAC** [comment]
Closing as this will be picked up with general regression fixing required for V3
