### ISSUE TITLE
Compile issue while running ibex_core_tracer example

### ISSUE THREAD

**Issue by raulbehl** [lowRISC/ibex#181]
Hi, 

I am running into compile issues while trying to run the `ibex_core_tracer` example using `fusesoc`.  I guess the issue is in the way `timescale` value is specified on the command-line. 

Updating the timescale option from `timescale=1ns/1ns` to `timescale 1ns/1ns` should fix it.

**Comment by towoe** [comment]
Hi, thanks for reporting this. What tool and which version are you using? I did a quick check and I guess at some point both options have been a valid format.

**Comment by raulbehl** [comment]
I tried this out with Modelsim:

`Model Technology ModelSim ALTERA vlog 10.1e Compiler 2013.06 Jun 12 2013`

**Comment by raulbehl** [comment]
I guess Questasim supports the "=" in between the timescale directive and the value.

**Comment by towoe** [comment]
> I guess Questasim supports the "=" in between the timescale directive and the value.

Unfortunately I can not test this.

And regarding your Modelsim version, in general I would not change something to support an old version of a tool, but if this is something that works then for all versions I think it makes sense.
The documentation on this is rather thin, so I guess it is based more on tests.
And for reference, the original option was adopted from a [fusesoc tutorial](https://fusesoc.readthedocs.io/en/latest/tutorials/3-tool_options.html).

**Comment by raulbehl** [comment]
Can you point me to the recommended version? I have tried it on `Model Technology ModelSim SE vlog 10.3a Compiler 2014.04 Apr 13 2014` which also doesn't support it.

**Comment by towoe** [comment]
The general recommendation would be to use the latest version.
But we can also use the different format here if it does not break with newer releases.
If you want you can create a pull request for this?

**Comment by imphil** [comment]
Fixed in https://github.com/lowRISC/ibex/pull/192
