### ISSUE TITLE
[dv] Implement double fault loop detector

### ISSUE THREAD

**Issue by GregAC** [lowRISC/ibex#1823]
Add a double fault loop detector to the testbench. It should determine when Ibex has entered a loop of double faults and terminate the simulation after some configurable number of iterations (with a default e.g. 100).

By default is should exit with a fail but a configuration option should be supplied to enable exit with a pass (for tests where a double fault loop is the intended behaviour).

> estimate 4
> remaining 2022-10-12 1

**Comment by GregAC** [comment]
Implementation here: https://github.com/lowRISC/ibex/pull/1808/commits but not yet merged

**Comment by marnovandermaas** [comment]
I am encountering these double faults (or faults that happen when handling another fault) during some PMP tests. To get an infinte loop of instruction access fault exceptions you can do the following.
Clone this repo and branch: https://github.com/marnovandermaas/ibex/tree/catch-dv-double-faults
Specifically use this commit: https://github.com/marnovandermaas/ibex/tree/10f561a4ddc8a381583fe0d63b9fae23f9b3b003

And then run the following command inside `dv/uvm/core_ibex`:
```
make -j1 --keep-going IBEX_CONFIG=opentitan ITERATIONS=1 TEST=riscv_pmp_full_random_test WAVES=0 COV=0 SEED=17397
```

**Comment by hcallahan-lowrisc** [comment]
> remaining 2022-10-12 1

**Comment by hcallahan-lowrisc** [comment]
Stil TODO:
- Add option to change the test result from a pass to a fail when the detector activates.
