### ISSUE TITLE
[dv] Automatically generate dump file

### ISSUE THREAD

**Issue by marnovandermaas** [lowRISC/ibex#1841]
Whenever I run a test with DV, I end up running the following command:
```console
riscv32-unknown-elf-objdump -D test.o > test.dump
```
It would be good to have the build environment do this automatically.

**Comment by hcallahan-lowrisc** [comment]
You should be able to run `make dump` to do this today. You can also run `make prettify` to create a column-aligned version of the ibex traces. :)

**Comment by marnovandermaas** [comment]
Ah right, thanks for pointing that out!
