### ISSUE TITLE
initialization the SP and GP

### ISSUE THREAD

**Issue by sadjadtu** [lowRISC/ibex#1867]
I am trying to simulate an already binary executable file. How can I initialize the stack pointer and global pointer?

**Comment by GregAC** [comment]
As in a binary you just have a .elf for and no source?

You could manually alter the register file to set specific SP and GP reset values though I suspect you'll run into other issues running a binary you don't have the source for.

If you can compile from source simply write your desired GP and SP values early in on the program init.
