### ISSUE TITLE
PMP Coverage Holes

### ISSUE THREAD

**Issue by ctopal** [lowRISC/ibex#1869]
- MPRV Effect cross is not getting hit for the cases: 
  - [ ] Privilege U->M Error 0 -> 1
  - [ ] Privilege U->M Error 1 -> 0
  - [x] Privilege M->U Error 1 -> 0
 
Note that `->` stands for MPRV changing LSU privilege mode.

- Sticky Bit Features for:
  - [ ] RLB
  - [x] MMWP
  - [x] MML

- Data Channel:
  - [x] No PMP region match && `mseccfg.mmwp` set.

- Instruction Channel 
  - [x] No PMP region match && `mseccfg` register values other than 0.
  - [x] Matching PMP region with NA4 mode (both allow and deny missing)

**Comment by ctopal** [comment]
- For Instruction channel:
  Plan for now is to work on a directed instruction stream to inject to a new PMP test (possibly named pmp_directed) to have a high priority pmpcfg register set as NA4 address mode with pmpaddr pointing to a executable code region. That could also write some random `mseccfg` values while running to cover some more holes.

**Comment by ctopal** [comment]
>remaining 2022-10-28 4

**Comment by GregAC** [comment]
Covered by estimate in https://github.com/lowRISC/ibex/issues/1944 so removing estimates from here.

**Comment by GregAC** [comment]
Closing this to leave #1944 for remaining tracking.
