### ISSUE TITLE
Error: Simulating with VCS

### ISSUE THREAD

**Issue by sadjadtu** [lowRISC/ibex#1889]
When I try to build:

fusesoc --cores-root=. run --target=sim --tool=vcs --setup --build lowrisc:ibex:ibex_simple_system --RV32E=0 --RV32M=ibex_pkg::RV32MFast --SRAMInitFile=./examples/sw/simple_system/hello_test/hello_test.vmem

I get this error:

INFO: Building
INFO: vcs -full64 -top ibex_simple_system -f lowrisc_ibex_ibex_simple_system_0.scr -o lowrisc_ibex_ibex_simple_system_0  -CFLAGS -I../../src/lowrisc_dv_crypto_prince_ref_0.1 -CFLAGS -I../../src/lowrisc_dv_secded_enc_0 -CFLAGS -I../../src/lowrisc_dv_scramble_model_0 -CFLAGS -I../../src/lowrisc_dv_verilator_memutil_dpi_0/cpp -lelf -CFLAGS -I../../src/lowrisc_dv_verilator_memutil_dpi_scrambled_0/cpp -lelf -xlrm uniq_prior_final -debug_access+r -sverilog
Makefile:4: recipe for target 'lowrisc_ibex_ibex_simple_system_0' failed

ERROR: make: vcs: Command not found
make: *** [lowrisc_ibex_ibex_simple_system_0] Error 127

ERROR: Failed to build lowrisc:ibex:ibex_simple_system:0 : '['make']' exited with an error: 2

**Comment by GregAC** [comment]
> ERROR: make: vcs: Command not found

Looks like VCS isn't available in your environment. This lies outside the scope of the Ibex DV flow and how VCS access is setup is specific to your environment.
