### ISSUE TITLE
[doc] No register file write enable glitching in documentation

### ISSUE THREAD

**Issue by ctopal** [lowRISC/ibex#1893]
It looks like we do not mention write enable glitch checking as a security countermeasure neither in register file page or in security page. It might be good to have it at least somewhere.

**Comment by ctopal** [comment]
@andreaskurth @GregAC Should I tag this as a V2S issue or like a low priority post M2 issue?

**Comment by andreaskurth** [comment]
I think we should document this before declaring V2S, and it can be done quickly.
