### ISSUE TITLE
Mismatch of dcsr.prv when interrupt followed by a debug request

### ISSUE THREAD

**Issue by Saad525** [lowRISC/ibex#1919]
## Observed Behavior

When there is an interrupt from U-mode followed by debug request, Ibex fetches the first instruction of the handler and when the debug request comes in, it takes it and jumps to corresponding address. Privilege mode already switched to M-mode and after debug request, when dcsr is read, dcsr.prv is 'b11.

![wave](https://user-images.githubusercontent.com/55890346/200887006-145b9916-c07a-4703-81ec-59141cd0a49f.png)

## Expected Behavior

Since we are feeding Spike with debug request or nmi interrupt (when multiple interrupts happen back to back before previous interrupt handler's first instruction execution), it doesn't have the transition from U-mode to M-mode, so we see dcsr.prv = 'b00 from Spike.

It seems that changes might be needed in Ibex cosim.

## Steps to reproduce the issue

```
cd dv/uvm/core_ibex
make --keep-going IBEX_CONFIG=opentitan SIMULATOR=xlm ISS=spike ITERATIONS=1 SEED=23054 TEST=riscv_assorted_traps_interrupts_debug_test WAVES=1
```

## My Environment

**Operating system:**

Ubuntu Linux 20.04

**Version of the Ibex source code:**

ba527fed80ccd3d98f47f01a712dbb60f5d53860 (Draft PR)

/cc @GregAC @hcallahan-lowrisc @ctopal 

> estimate 8

**Comment by GregAC** [comment]
estimate range: 4 - 8
