### ISSUE TITLE
Documentation discrepancies around integrity errors and exceptions

### ISSUE THREAD

**Issue by msfschaffner** [lowRISC/ibex#1920]
https://ibex-core.readthedocs.io/en/latest/03_reference/exception_interrupts.html#internal-interrupts claims that 
```
Load integrity error internal interrupt. Only generated when SecureIbex == 0. mtval gives the faulting address. The interrupt will be taken at most one instruction after the faulting load. In particular a load or store immediately after a faulting load may execute before the interrupt is taken.
```
Isn't it the other way round - i.e., isn't the error only generated when `SecureIbex == 1`?

**Comment by GregAC** [comment]
> Isn't it the other way round - i.e., isn't the error only generated when SecureIbex == 1?

Correct, I'll open an PR to fix the typo

**Comment by vogelpi** [comment]
Thanks @GregAC !

**Comment by msfschaffner** [comment]
Another question: is this table [here](https://ibex-core.readthedocs.io/en/latest/03_reference/exception_interrupts.html#exceptions) missing the `InstrMisalinged` exception?

**Comment by GregAC** [comment]
> Another question: is this table [here](https://ibex-core.readthedocs.io/en/latest/03_reference/exception_interrupts.html#exceptions) missing the `InstrMisalinged` exception?
> 
> We seem to be defining this in ibex.h on the OpenTitan side:
> 
> ```c
> /**
>  * An Ibex exception type.
>  *
>  * This enum is used to decode RISC-V exception causes generated by Ibex.
>  */
> typedef enum ibex_exc {
>   kIbexExcInstrMisaligned = 0,
>   kIbexExcInstrAccessFault = 1,
>   kIbexExcIllegalInstrFault = 2,
>   kIbexExcBreakpoint = 3,
>   kIbexExcLoadAccessFault = 5,
>   kIbexExcStoreAccessFault = 7,
>   kIbexExcUserECall = 8,
>   kIbexExcMachineECall = 11,
>   kIbexExcMax = 31
> } ibex_exc_t;
> ```

No it isn't, you cannot generate instruction misaligned exceptions when you have the 'C' extension. I've fixed the ``IbexSecure`` issue and added a clarification for the instruction misaligned exception here: https://github.com/lowRISC/ibex/pull/1957

**Comment by msfschaffner** [comment]
Great, thanks for the clarification!
