### ISSUE TITLE
there is error when I  make

### ISSUE THREAD

**Issue by Zhengshuhang** [lowRISC/ibex#1932]
Hi, I'm a beginner in risc-v DV,I made sure I set up the environment carefully,but when I run 
`make --debug`
there is following error:

<img width="462" alt="image" src="https://user-images.githubusercontent.com/77762994/201695525-20660fb6-b9f5-43b3-ba83-db08b5014ea3.png">
 
the compile_tb.log:

[compile_tb.log](https://github.com/lowRISC/ibex/files/10004334/compile_tb.log)

can you help me?

**Comment by GregAC** [comment]
> /opt/cadence/XCELIUM1803/tools/bin/64bit/xmsc_run: 12: [: lnx86: unexpected operator

From your log, almost looks like `xmsc_run` is a shell script that's corrupt or running under the wrong shell.

I'd suggest trying a newer version of Xcelium but as this looks to be a tooling/environment issue rather than something Ibex related I'll close this now.
