### ISSUE TITLE
Wrong encoding of EXC_CAUSE_ILLEGAL_INSN

### ISSUE THREAD

**Issue by taoliug** [lowRISC/ibex#195]
This issue seems to be introduced in this commit
https://github.com/lowRISC/ibex/commit/c2fffe04406287bc7e1be3962999f0f6b44ebe87#diff-ef03dc5b772f9745e0a161472ea79c60R190

EXC_CAUSE_ILLEGAL_INSN should be 2 according to RISC-V privileged mode spec

**Comment by vogelpi** [comment]
Hi @taoliug 
thanks for reporting this! I must have accidentally introduced this bug. Sorry for that. I will fix it immediately.
