### ISSUE TITLE
Ibex tracer - compressed instructions

### ISSUE THREAD

**Issue by udinator** [lowRISC/ibex#197]
Hi,
Would it be possible to have the Ibex tracer indicate that an instruction is compressed, and if so, log the compressed instruction name? This would bring the log file closer in similarity to Spike log files, and would make debugging regression failures a bit easier to do.
Not sure if this complies with RVFI spec though.
Thanks!
Udi

**Comment by imphil** [comment]
Sure, that's possible. We have the `rvfi_insn` signal, which contains the original (compressed) instruction. (The non-standard `rvfi_insn_uncompressed` signal always contains the uncompressed instruction. This one is currently used by ibex_tracer.)

We have two options going forward:
- Either you open a PR which extends `ibex_tracer` to include the compressed instruction.
- Or you let me know how you'd like the logs to look and I'll implement it.

**Comment by udinator** [comment]
Current ibex trace logs are below:
![Screenshot from 2019-07-31 10-37-14](https://user-images.githubusercontent.com/16736281/62234432-867bf580-b37f-11e9-96b6-ecf0d713ba7d.png)
![Screenshot from 2019-07-31 10-38-44](https://user-images.githubusercontent.com/16736281/62234439-8aa81300-b37f-11e9-9b39-0e7283f2f886.png)

I was just referring to denoting the instructions as compressed (such as c.addi, etc...) like Spike logs do:
![Screenshot from 2019-07-31 10-37-00](https://user-images.githubusercontent.com/16736281/62234481-9d224c80-b37f-11e9-9523-acf7c7fcad10.png)
![Screenshot from 2019-07-31 10-38-28](https://user-images.githubusercontent.com/16736281/62234490-a3182d80-b37f-11e9-88ef-8cb01cb9be9f.png)

I was just thinking it could be efficient for the ibex logs to show the compressed instruction name (c.li, c.addi, c.lui, etc...) to match what Spike shows and give a better idea of which instructions are compressed or not. Thanks!
