### ISSUE TITLE
Prefetcher busy_o

### ISSUE THREAD

**Issue by darbaria** [lowRISC/ibex#20]
Two asserts that check that busy_o in the prefetch_buffer can change its state are failing. The assert that checks that once busy_o is low it can go high in future is failing in two clock cycles; this one I'm more inclined to say it can be a setup issue, as I'm still not fully familiar with the design; the interfaces are not fully specified either so difficult to say. However, the assert that says once you're busy you should become not busy eventually is also failing at 6 clock cycles suggesting it is possible to put the prefetcher in the busy state forever.

**Comment by vogelpi** [comment]
I can't find these assert statements, they seem no longer to be there. We have clarified how the instruction interfaces work some time ago. I am thus closing this issue now.
