### ISSUE TITLE
Verify memory access fault

### ISSUE THREAD

**Issue by taoliug** [lowRISC/ibex#202]
Randomly assert error bit for instruction fetch and load/store. 
Expect the core to raise memory access fault exception
Verify the fault load instruction won't modify GPR
Verify the context of the exception is captured correctly in privileged CSRs
- mstatus, mcause, mepc, mtval

**Comment by imphil** [comment]
Also see #87

**Comment by udinator** [comment]
This feature of the core has been tested, finding a bug regarding to a prefetcher error after an I-Mem fault, and a bug regarding faulting misaligned data memory accesses. Fixes have been merged for these bugs, so will close this tracking issue.
