### ISSUE TITLE
Preparing metadata (setup.py) ... error  for install pyboolector

### ISSUE THREAD

**Issue by athurwo** [lowRISC/ibex#2048]
[fso💀fso ibex]💯🥊sudo pip install pyboolector
[sudo] password for fso: 
Collecting pyboolector
  Using cached PyBoolector-3.2.2.20230110.4.tar.gz (21 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [7 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-wapqpg76/pyboolector_2df15e09845a44aea01e63ea84480e9b/setup.py", line 14, in <module>
          with open(cmakelists_txt, "r") as f:
               ^^^^^^^^^^^^^^^^^^^^^^^^^
      FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-install-wapqpg76/CMakeLists.txt'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by rswarbrick** [comment]
Hmm, that's odd! I'm not sure it's related to Ibex, though (I just checked, and "boolector" doesn't appear in our repo at all!)

If you're still seeing problems with thin, maybe the raise an issue there?

**Comment by athurwo** [comment]
> 
in vendor/google_riscv-dv/requirements.txt ,  there have a pyvcs, this package need boolector.
