### ISSUE TITLE
Verify debug interface

### ISSUE THREAD

**Issue by udinator** [lowRISC/ibex#205]

**Comment by imphil** [comment]
See also #168

**Comment by arghimat** [comment]
Is the software debugging currently working for ibex? Is there a Debug Module (DM), Debug Module Interface (DMI) and Debug Transport Module (DTM) as specified by the RISCV specification already available or planned in this project? I would like to use OpenOCD with ibex but I am not sure if this project will provide the required debug infrastructure or this is not in the scope.

**Comment by imphil** [comment]
You can use the debug module from PULP https://github.com/pulp-platform/riscv-dbg/ with Ibex.

**Comment by udinator** [comment]
All features of Debug-Mode currently implemented have been tested, and a main issue was found with how `dret` was treated in normal execution modes. Fixes have been pushed for this bug, so will close this issue as testing is complete.
