### ISSUE TITLE
Branch Instrution Format in ibex_tracer

### ISSUE THREAD

**Issue by hyperion009** [lowRISC/ibex#2069]
I realized that  branch instruction is decoded into a format with register destion (RD), but a branch instruction in spec has no rd.
![1691498882312](https://github.com/lowRISC/ibex/assets/30075118/8e0b06d8-da16-4c35-a74c-68b0a8b18aa7)
At the same time, that instructions from Spike's simualtion have not RD!

**Comment by rswarbrick** [comment]
The RD here was removed in October 2021, by 873e2281c. Please check with a recent version of the code.
