### ISSUE TITLE
directed_test_schema.py pydantic error

### ISSUE THREAD

**Issue by omerkarslioglu** [lowRISC/ibex#2077]
When I run dv with makefile in core_ibex, pydantic gives error. I think it should be updated.

The message is like:
    @pydantic.root_validator()
  File "/home/tutel/.local/lib/python3.8/site-packages/pydantic/deprecated/class_validators.py", line 228, in root_validator
    raise PydanticUserError(
pydantic.errors.PydanticUserError: If you use `@root_validator` with pre=False (the default) you MUST specify `skip_on_failure=True`. Note that `@root_validator` is deprecated and should be replaced with `@model_validator`.

I changed somewhere in the python script according to error message but i didn't succeed.

**Comment by rswarbrick** [comment]
We're working around this by forcing an older version of Pydantic in `python-requirements.txt`. To get that, you'll want to use something like `pip3 install -r python-requirements.txt`.

But see #2058, which should allow recent versions of Pydantic too.
