### ISSUE TITLE
Strange performance counters after following Simple System guide

### ISSUE THREAD

**Issue by noas1019** [lowRISC/ibex#2101]
Hi, I closely followed the guide in https://github.com/lowRISC/ibex/blob/master/examples/simple_system/README.md to try and simulate Ibex to run some tests, but I get strange results from the performance counters no matter the test used (everything but cycles and instructions retired is 0).  I've attached the results of hello_test and dit_test respectively, can someone point me to where the simulation is going wrong?
![hello_test](https://github.com/lowRISC/ibex/assets/55861223/e48b192e-be0e-4c35-942d-23935ebb297d)
![dit_test](https://github.com/lowRISC/ibex/assets/55861223/4c828e0e-6582-41be-b562-15138a68126e)

## My Environment

I'm running Ibex in Visual Studio Code using an Ubuntu wsl terminal.  All the pre-requisites in the simple_system guide were installed (along with RISC-V toolchain from https://github.com/lowRISC/lowrisc-toolchains/releases/tag/20230811-1), and the commands to build the simulation + software and run them are straight from the guide.

**EDA tool and version:**

N/A

**Operating system:**

Ubuntu 22.04.2 LTS

**Version of the Ibex source code:**

7aec1404f1d406ff9d3e68f9844387fc9f44c9ac

**Comment by rswarbrick** [comment]
Hmm, this is a bug in our simple system guide. Kind of! The reason we're getting zeroes here is that the default configuration that you're picking has no performance counters. Unsurprisingly, this means that the counter numbers that are reported at the end of the simulation are all zero.

Fixes that we need to do:
1. Update the simple system documentation to use `ibex_config.py`. Something like this should work: `fusesoc --cores-root=. run --target=sim --setup --build lowrisc:ibex:ibex_simple_system $(util/ibex_config.py opentitan fusesoc_opts)`
2. Update the simple system wrapper C++ code not to report numbers that it doesn't know.
