### ISSUE TITLE
Cosim verification seed and randomization dependency.

### ISSUE THREAD

**Issue by omarbesta** [lowRISC/ibex#2125]
Is the Cosim verification heavily dependent on the randomization and the seed?
I get failures sometimes and I have to change the seed for some tests to pass.

## My Environment

**EDA tool and version:** Questasim 2023.1

**Operating system:** Linux-64 CentOS 7.9

**Version of the Ibex source code:** df88055aa38868451ce90d7fcc2bbf172a2dc8a0

**Comment by rswarbrick** [comment]
Hi there.

Well, the seed controls several things including the contents of the randomised binary that gets run. If things are failing with a given seed, it's probably worth investigating (probably by opening an issue with details of the seed and what happens).
