### ISSUE TITLE
ERROR: Conflicting requirements:o Ibex

### ISSUE THREAD

**Issue by prathameshkhairnar1999** [lowRISC/ibex#2139]
I am trying to work with older version of ibex which gas led.c example and i am trying to build it with zed board. I am getting an following error
ERROR: Conflicting requirements:
Requirements: 'lowrisc_ibex_top_artya7 == 0.1-0' <- 'lowrisc_ibex_fpga_xilinx_shared >= 0-0' <- 'lowrisc_prim_ram_2p >= 0-0'
    +lowrisc_ibex_fpga_xilinx_shared-0-0 was ignored because it depends on missing packages
Requirements: 'lowrisc_ibex_top_artya7 == 0.1-0' <- 'lowrisc_ibex_fpga_xilinx_shared >= 0-0'
    lowrisc_ibex_top_artya7-0.1-0 requires (+lowrisc_ibex_fpga_xilinx_shared-0-0)
Requirements: 'lowrisc_ibex_top_artya7 == 0.1-0'
    Install command rule (+lowrisc_ibex_top_artya7-0.1-0)

Failed to resolve dependencies for lowrisc:ibex:top_artya7:0.1
Please help me.

**Comment by rswarbrick** [comment]
Hi there,

I'm not sure we're going to be able to help without a bit more information. You'll probably need to post with the commands that you are running, together with the fusesoc failure that you see.

I'd also suggest trying the latest version of Ibex. I'd be very surprised if any of the changes that have landed in the last year or two could cause you a problem.

Please re-open this with more information if we can help further.
