### ISSUE TITLE
Make ibex_tracer Verilator-compatible

### ISSUE THREAD

**Issue by imphil** [lowRISC/ibex#220]
It should be possible to use a coding style for the tracer which works in Verilator, making this helpful tool available there as well.

**Comment by raulbehl** [comment]
This is work in progress (I actually have the branch ready just need some style-nit fixes before raising a PR). I have used #262 as my starting point for this. Should I wait until #262 is merged and then open a pull-request?

**Comment by imphil** [comment]
Feel free to open a PR right away. This allows us to start with the review right away, and you can then rebase before merging.

**Comment by vogelpi** [comment]
The tracer is now Verilator compatible. This has been added starting with lowRISC/ibex#360. I am thus closing this issue now.
