### ISSUE TITLE
Verify WFI does not cause instruction fetches

### ISSUE THREAD

**Issue by udinator** [lowRISC/ibex#269]
Need to add functionality to TB to verify that upon encountering a WFI instruction, ibex does not perform any instruction fetches before any stimulus is driven by the testbench.

**Comment by tjaychen** [comment]
udi,
can i also ask that we check the core finishes all pending transactions
before asserting an idle indication to the outside world?

**Comment by imphil** [comment]
@tjaychen We don't signal "idle" to the outside world yet, that's #258

**Comment by udinator** [comment]
This feature has been tested, and `core_sleep_o` successfully indicates to the outside world that the core is sleeping and that all pending transactions have been finished and no more transactions are being fetched. This issue will be closed.
