### ISSUE TITLE
Accessing debug CSRs while not in debug mode

### ISSUE THREAD

**Issue by vogelpi** [lowRISC/ibex#275]
The RISC-V Debug Spec v.0.13.2 (p.41) mandates that the core debug CSRs `dcsr`, `dpc`, `dscratch0` and `dscratch1` must not be accessible if not in debug mode. Currently, Ibex always allows accesses to these. This should be changed.

See also pulp-platform/riscv#136.

**Comment by davideschiavone** [comment]
Same for RISCY, we have the same issue @bluewww

**Comment by davideschiavone** [comment]
https://github.com/pulp-platform/riscv/issues/136
