### ISSUE TITLE
Replace core_id and cluster_id parameters in favour of a single hartid parameter

### ISSUE THREAD

**Issue by asb** [lowRISC/ibex#29]
Ibex should allow system integrators to directly specify the hartid using whatever scheme makes most sense for their design. Currently core_id and cluster_id must be specified - this makes sense for the PULP use case, but will require some gymnastics for users who have a different hartid generation scheme.

[EDIT: "gymnastics" is hyperbolic given they're just concatenated - but you get my point. An integrator may also want a hartid that is greater than 10 bits in length]

**Comment by imphil** [comment]
I think your use of gymnastics is very much in line with my physical exercise routine :smile:
