### ISSUE TITLE
Compressed tracer load/store issue

### ISSUE THREAD

**Issue by udinator** [lowRISC/ibex#322]
Hi @raulbehl,
I'm seeing some weird behavior with the tracer (from #262) involving long runs of compressed `lw` or `sw` instructions, below is the disassembled instruction sequence that is getting executed:
![Screenshot from 2019-09-16 13-19-46](https://user-images.githubusercontent.com/16736281/64990442-afe7d680-d884-11e9-96a3-1c03d15861ca.png)
And, below is what Ibex tracer is printing out for the exact same sequence:
![Screenshot from 2019-09-16 13-20-56](https://user-images.githubusercontent.com/16736281/64990526-d3128600-d884-11e9-985a-0fb5a02ec7be.png)

**Comment by raulbehl** [comment]
Hi @udinator, 
Thank you for reporting this. The behaviour for compressed load/stores is same as uncompressed load/stores and the issue should be seen for there as well?  I'll push a fix for this soon.

**Comment by imphil** [comment]
I'm on it (it's just a swap of the register and the immediate). I'll integrate it into some changes I'm doing on the tracer now.

**Comment by udinator** [comment]
Hi @imphil - Regarding the recent updates to the ibex tracer, I'm seeing that for the `c.addi16sp` instruction, the `rd` and `rs1` register values are not being shown, so the log entry for this instruction looks like below:
![Screenshot from 2019-10-03 16-21-34](https://user-images.githubusercontent.com/16736281/66173622-e86a0d00-e605-11e9-9c6c-4853fa257ac2.png)
