### ISSUE TITLE
Local CI tests

### ISSUE THREAD

**Issue by MarekPikula** [lowRISC/ibex#341]
What do you think about making a local CI test solution based on Docker container? Currently that's how I'm testing my changes before commiting. I have simple Dockerfile doing pretty much all the initialisation part from `azure-pipelines.yml` and then I'm executing next commands by hand.

Would anyone be interested in PR with this? I could polish the Dockerfile and write simple script executing all the tests.

**Comment by asb** [comment]
Thanks for the suggestion Marek. I think independently of `Dockerfile`s, moving more of test logic that is currently in `azure-pipelines.yml` to a separate script is worthwhile.

For an in-tree Dockerfile we'd ideally have a story on making sure it doesn't become stale. I'm not sure how many people the Dockerfile would help, vs having clear instructions on dependencies and letting people handle those dependencies in the way they prefer (Docker, local installation, VMs, LXD, Podman, ...).

**Comment by MarekPikula** [comment]
Well, my solution is basically fully based on Pipelines script, so anyone making changes to Pipelines would also make changes to Dockerfile.

My solution is entirely self-contained, so in order to run tests you just run a Docker image with whatever tool you're using with volume pointing to current directory and everything is done automatically as in Pipelines. We could even build an image for Docker Hub, so it would be just one command to run all tests.

**Comment by imphil** [comment]
@MarekPikula Please open a PR if you have something to look at; I'm currently traveling and will go back to look at Ibex CI topics in a week from now after ORConf.

**Comment by MarekPikula** [comment]
Sure, I'll polish it today and will post PR.

**Comment by MarekPikula** [comment]
Where should I put all the related files? Maybe separate folder `docker` in main tree?

**Comment by imphil** [comment]
We do have a docker environment for a while now, closing.
