### ISSUE TITLE
Bump minimum Verilator version

### ISSUE THREAD

**Issue by imphil** [lowRISC/ibex#376]
We currently don't document a specific version of Verilator. We use 4.016 in our CI at the moment, but the simulation should work with older versions at well. Instead of now documenting a arbitrary number, let's wait until we have a good reason for a bump.

Currently we have the following requirements:
- at least 4.020: Remove workaround as discussed in #372

Extend this issue over time, and then decide once we found a good version which is widely available to our users.

**Comment by vogelpi** [comment]
We are checking for supported tool versions including Verilator since 3a078865c87ab82931a5dfa7cbc61c64a9ef8d1a. I am thus closing the issue.
