### ISSUE TITLE
Add support for FENCE.I instruction

### ISSUE THREAD

**Issue by GregAC** [lowRISC/ibex#391]
As raised in https://github.com/lowRISC/ibex/issues/365 FENCE.I can be emitted by debuggers leading to an illegal instruction exception on Ibex as it doesn't support it.

Support should be fairly trivial (flush prefetch buffer and pipeline then continue)

**Comment by MarekPikula** [comment]
@GregAC what is your status on this? I would like to be as much upstream as possible with my Ibex and `nop` workaround is not particularly optimal.
