### ISSUE TITLE
ebreak instruction broken

### ISSUE THREAD

**Issue by GregAC** [lowRISC/ibex#393]
The ebreak instruction is broken when executing in debug mode or when dcsr.ebreakm is set. The prevents the pulp riscv dbg module from working correctly as it extensively uses this instruction.

The root cause is the ID stage gets flushed as the controller transitions into DBG_TAKEN_ID but should probably remain valid and flush as part of the DBG_TAKEN_ID handling. Transitions into DBG_TAKEN_IF may have similar issues.

I have a trial fix but more thought is required before I produce a PR.

**Comment by GregAC** [comment]
Ah yes I had noticed that too, should be easy enough.

**Comment by MarekPikula** [comment]
I just tested `master` Ibex and indeed debugging doesn't work anymore.
