### ISSUE TITLE
Switch back to upstream Sphinx package

### ISSUE THREAD

**Issue by imphil** [lowRISC/ibex#41]
Once a Sphinx release with sphinx-doc/sphinx#6364 is out we need to switch back to it, we're currently using a fork to fix a bug.

https://github.com/lowRISC/ibex/blob/62185d054ef937d5ceb74c85797245f481016fb3/doc/requirements.txt#L2

**Comment by wallento** [comment]
That's good, important to switch back to an actual pip release (sphinx>=2.0.2)

**Comment by wallento** [comment]
It is merged and scheduled for 2.0.2
