### ISSUE TITLE
Missing description of input signal from documentation.

### ISSUE THREAD

**Issue by ikarageo** [lowRISC/ibex#44]
Hi,
Description of input "data_err_i" of the data memory interface is missing from documentation. This signal is currently used only for an assertion. Since it is a top level input, I believe it would be better for the user to read about it in the documentation instead of figuring it out from the RTL.

Best,
Ioannis

**Comment by imphil** [comment]
Absolutely. Would you mind opening a PR adding documentation for that signal?

**Comment by vogelpi** [comment]
Actually, I could do that as I am about to create a new PR for letting the core evaluating that signal and trigger exceptions.
