### ISSUE TITLE
[assertions] consider functional coverpoints

### ISSUE THREAD

**Issue by sjgitty** [lowRISC/ibex#452]
It would be nice to add some functional coverpoints to the Ibex design
to augment the verification efforts, and potentially take advantage of
some formal methods. I'm just starting the conversation here, but we
could suggest some coverpoints as follow-up in this issue.

CC @udinator

**Comment by rswarbrick** [comment]
@GregAC: This presumably ties in to the functional coverage work you've been doing. I think we can probably just close this issue, since we've started the work now. What do you think?

**Comment by GregAC** [comment]
Yup I think so, still plenty to do here but the foundation is in.
