### ISSUE TITLE
Optional U-Mode

### ISSUE THREAD

**Issue by MarekPikula** [lowRISC/ibex#467]
Would it be feasible to make U-Mode enable a core parameter like PMP?

I'm sure there are some use cases where it's not really needed, yet as small logic utilization as possible is required. Is the U-Mode so tightly integrated into the core that it cannot be easily separated as a parameter?

**Comment by tomroberts-lowrisc** [comment]
We didn't parameterize it as it has such a small overhead (just a handful of extra flops). Is there a particular part where you think area could be saved?

**Comment by MarekPikula** [comment]
Not really. To be honest I thought the overhead is bigger than a handful of extra flops.

**Comment by tomroberts-lowrisc** [comment]
Yeah it's surprisingly small. If you're interested, all of the changes to implement it are in this commit 2aacd2b98be61fa4c9b633d1ddba9d1d5c894faf

**Comment by MarekPikula** [comment]
Looks really good :+1: Yeah, so in the end it's indeed not needed to make it a parameter. Thanks for quick response.
