### ISSUE TITLE
An higher prio interrupt routine is interrupted by lower prio IRQ

### ISSUE THREAD

**Issue by vit82** [lowRISC/ibex#482]
When executing a higher priority interrupt routine, it can be interrupted by a lower prio interrupt if MIE is set high and high prio IRQ source cleared. Is it an intended implementation? 

Below is a screenshot where fast_irq_i[0] and fast_irq_i[1] occur simultaneously. First, fast_irq_i[1] is being served. But after I clear fast_irq_i[1] source & set MIE high, the routing is preempted by fast_irq_i[0] . Once fast_irq_i[0] routine is complete, the rest of fast_irq_i[1] is completed.
![image](https://user-images.githubusercontent.com/55279763/69151649-b3494980-0ae3-11ea-97a0-925c07b3f40c.png)

**Comment by vit82** [comment]
[firmware_rv32imc.lss.txt](https://github.com/lowRISC/ibex/files/3864062/firmware_rv32imc.lss.txt)
Attaches is FW listing file.

**Comment by vogelpi** [comment]
Hi @vit82 ,
yes, that is intended behavior. As far as I know, the priority only matters if multiple interrupt lines are high and the core needs to decide which one to start handling first.

**Comment by vit82** [comment]
Alright, I see it's possible to implement the above mentioned function by adding extra logic outside CPU. But it would require replication of arbitration logic etc. So isn't it more optimal to put everything inside CPU core? Or may there's a use case when higher prio routine needs to be preempted by a lower prio routine?

**Comment by vogelpi** [comment]
This behavior can be implemented in software: Before re-enabling interrupts by setting `mstatus.MIE` to 1'b1, the content of `mie` has to be modified. This CSR holds the interrupt enable of the individual interrupts.

For example when handling fast interrupt no. 1 (`mfip[1]`, interrupt ID 17), all `mie[17:0]` has to be set to 0. The interrupt routine is then only interrupted by fast interrupt no. 2 - 14 (ID 18 - 30).

**Comment by vit82** [comment]
Ok, your suggested approach works. Though it increases interrupt service overhead.

**Comment by imphil** [comment]
Please look into an external interrupt controller, like PLIC or CLIC, if you are interested in more hardware processing for your interrupts.
