### ISSUE TITLE
Referring to Document revisions

### ISSUE THREAD

**Issue by eroom1966** [lowRISC/ibex#505]
We have released a simulation model of the lowRISC processor as part of the riscvOVPsim simulation engine. We would like to refer to the documentation based upon the date at which the implementation was derived, but it seems the 'online docs' are always referring to the HEAD/Master revision

How can we refer to a copy of the docs for the specific implementation ?
Are you intending to use the release mechanism of versioning of docs ?

**Comment by imphil** [comment]
Document revisions match Ibex revisions, but there is currently no tagged release of Ibex. We plan to do one in not too distant future, but no specific dates have been set yet. Up until this point, you can refer to the git commit hash, and need to build the documentation yourself from this git revision.
