### ISSUE TITLE
Implement single-cycle multiplier

### ISSUE THREAD

**Issue by imphil** [lowRISC/ibex#527]
Currently ibex ships with two multiplier implementations, a fast one and a slow one. Both of them require multiple cycles. Implement an even faster multiplier within one cycle.

**Comment by ganoam** [comment]
Hi everyone,
I have drafted a single cycle multiplier implementation (PR: #559). It is largely just a simplification of the fast implementation. It results in 4 DSP48E1 primitive blocks, in the Artya7-100 example, where the 'fast' implementation used the same block just once.

**Comment by vogelpi** [comment]
I am closing this issue as the corresponding PR has been merged.
