### ISSUE TITLE
Track RISC-V Compliance Framework

### ISSUE THREAD

**Issue by towoe** [lowRISC/ibex#605]
It looks like [RISCOF](https://riscof.readthedocs.io/en/latest/) is v2 of riscv-compliance as mentioned in https://github.com/riscv/riscv-compliance/pull/80#issuecomment-585485427.
It is still WIP, but as I was not aware of this and I am not sure how well it is known, I wanted to raise awareness for the new framework.

**Comment by imphil** [comment]
Interesting find! Let's see how that one evolves.

**Comment by towoe** [comment]
https://github.com/riscv/riscv-compliance/issues/90#issuecomment-747524231

Looks like it evolved, will check it out.

**Comment by imphil** [comment]
Nice! https://riscof.readthedocs.io actually looks promising.

**Comment by towoe** [comment]
Closing in favor of issue #1233
