### ISSUE TITLE
gdb support

### ISSUE THREAD

**Issue by jrrk2** [lowRISC/ibex#652]
By default the ibex repository does not include riscv-dbg (gdb) support. Such support is available within the opentitan repository as part of a much larger project. I have modified the basic ibex example to include gdb support for a total of 4001 LUTs, by crudely copying relevant modules from opentitan and modifying to suit the original example style. I believe this contribution would be attractive to potential commercial customers who will naturally assume debug support as a prerequisite. The question is, how to format these changes to ease merging with the no debug ibex FPGA example (tested on Arty-A7-A100)

[my fork](https://github.com/lowRISC/ibex/pull/654)

**Comment by imphil** [comment]
Thanks for your work on this @jrrk2. 

I'm not convinced the Ibex repository is the right place to put such an example. Adding debug support needs much more SoC infrastructure than we have currently, including an extended "bus" implementation. I'd therefore leave the simple system as simple as it is for now, and redirect people to more fully-featured SoC implementations if they are looking for examples on how to integrate a RISC-V Debug Implementation with Ibex, with OpenTitan and (probably) PULPissimo being two examples for that.

Maybe it would be a viable path forward to link these sample integrations in the docs somewhere? And maybe we can also include a more minimal Ibex example that you put together in #654 that you keep in a personal repository on GitHub?

**Comment by jrrk2** [comment]
Closing this issue because the solution is discussed in https://github.com/lowRISC/ibex/pull/654
