### ISSUE TITLE
[bitmanip] Ternary Bit-Manipulation Instructions cmix, cmov, fsl, fsr[i]

### ISSUE THREAD

**Issue by ganoam** [lowRISC/ibex#708]
Hi Guys,

For the bitmanip ternary instructions, three registers have to be read. Since our register file only has two read ports, I will implement those instructions in two cycles.

I will take inspiration from the existing structures which require pipeline stalls. As soon as I have a verified implementation I will again open a draft PR.

**Comment by vogelpi** [comment]
Sounds like a plan @ganoam .

**Comment by ganoam** [comment]
A PR is available: #746

**Comment by ganoam** [comment]
Ternary bitmanipulation instructions have been merged.
