### ISSUE TITLE
number of breakpoints 

### ISSUE THREAD

**Issue by Sarafim** [lowRISC/ibex#788]
Hi,
As far as I understood from the doc, it is possible to have only 1 hw breakpoint via tdata2 register.
Is it true? and is it any possibility to have more then 1 hw breakpoint?

Thanks in advance!

**Comment by tomroberts-lowrisc** [comment]
Yes that's correct, only one is currently supported by the hardware. It wouldn't be too much more work to add support for more, but it's not something we have planned at the moment.

**Comment by Sarafim** [comment]
got it, thank you!
