### ISSUE TITLE
About I2C master code for MCU zero MCU

### ISSUE THREAD

**Issue by Tott12** [lowRISC/ibex#798]
Dear Experts, 

I have a hobby project while MCU zero is connected to an amplifier via I2C and want to send and receive bunch of data over I2C.
The issue is I cannot find reference code to do so, with TI /STM or NXP MCU a wrapper is always provided but here found my self stuck.
So MCU zero should be in master mode controlling the I2C device connected.

Can you please guide me on where to find a reference code to handle I2C in master mode ?
Thanks so much in advance.
Franchisco.

**Comment by imphil** [comment]
Thanks for your interest in Ibex. Probably Ibex is not the right starting point for you: Ibex is only a CPU core, what you're looking for is a full microcontroller, which extends the CPU with peripherals like I2C, a memory, and many things more. There are multiple System-on-Chip designs which use Ibex internally, for example pulpissimo or OpenTitan. I'd recommend having a look at https://github.com/pulp-platform/pulpissimo as a starting point.
