### ISSUE TITLE
Support for PMP

### ISSUE THREAD

**Issue by wallento** [lowRISC/ibex#8]
Implement Physical Memory Protection (PMP) as per privspec 1.10. My team is planning to work on that.

**Comment by davideschiavone** [comment]
It's currently under development for Riscy in the branch MPU_branch.
once it is stable and well tested it will be merged into the master.
Then we can try to port it to zero-riscy.
Any help is welcome of course.

Best
Davide

**Comment by imphil** [comment]
@towoe did you already start implementing PMP in the past?

**Comment by towoe** [comment]
No sorry, haven't worked on that.

**Comment by wallento** [comment]
I did work on it and finally have access to my old work computer. Will check about it tomorrow!

**Comment by vogelpi** [comment]
PMP support has been added by @tomroberts-lowrisc as part of lowrisc/ibex#252. I am thus closing the issue.
