### ISSUE TITLE
Trigger cause

### ISSUE THREAD

**Issue by Sarafim** [lowRISC/ibex#833]
Hi,
I just noticed that the "2 - Trigger cause" is absent in the doc
![image](https://user-images.githubusercontent.com/17382041/80789775-b3229f00-8b95-11ea-88ab-d10091ad1a24.png)

**Comment by vogelpi** [comment]
Hi @Sarafim ,
thanks for filing this issue. Indeed, the trigger cause should be listed here as it is supported in the RTL if the `DbgTriggerEn` parameter is set.

I will prepare a PR to fix this. Or in case you have something ready, you can also open a PR.

Best,
Pirmin
