### ISSUE TITLE
Update documentation to run cache TB

### ISSUE THREAD

**Issue by imphil** [lowRISC/ibex#895]
The documentation at https://ibex-core.readthedocs.io/en/latest/verification.html#id1 lists command line options which don't exist in dvsim any more. Needs to be updated.

@rswarbrick

**Comment by rswarbrick** [comment]
Yep. I've also got some outstanding patches on the OT side, which will change the recommended commands slightly too. Let's fix this once everything has settled down.

**Comment by imphil** [comment]
https://ibex-core.readthedocs.io/en/latest/03_reference/verification.html#instruction-cache has this information now.
