### ISSUE TITLE
Adding new functionalities to RISCV

### ISSUE THREAD

**Issue by Fifiy** [lowRISC/ibex#897]
I'm a newbie and I have to work with Ibex as an exemple, first of all, I want to know how can we add new calculation functionalities ? Do we need to interact on the ALU directly ?

**Comment by rswarbrick** [comment]
Hi @Fifiy. I don't think that a GitHub issue is the best place for this discussion. Can I suggest that you [join Zulip](https://lowrisc.zulipchat.com/register/) and get in touch there?

**Comment by rswarbrick** [comment]
Hi again! Great to hear from you on Zulip. I'm going to close this issue now: please feel free to ask us more there, or file any bug reports here.
