### ISSUE TITLE
Question: trace comparison of external stimulus

### ISSUE THREAD

**Issue by kabylkas** [lowRISC/ibex#963]
Hi :wave: 

I have a difficulty understanding how is the trace comparison happens when external interrupts are present. 

From the figure that I got in Ibex manual, it seems like ISS is completely decoupled from the RTL during the execution. By looking at this, my guess is that ISS will not be aware of the change in execution flow when interrupt triggers and the traces will diverge. Does this mean that comparison will fail if there are interrupts?

Thank you,

![image](https://user-images.githubusercontent.com/8511359/84840920-c4b0f080-aff5-11ea-81f1-f3fc90e0f647.png)

**Comment by udinator** [comment]
Hi @kabylkas , thanks for the question!

You're correct in that the ISS will not be aware of any interrupt/debug triggers, and this will cause divergences in the trace logs.
To handle this, in tests like this, we disable instruction-by-instruction checking between the logs and just check the final values that end up stored in the register file, as this state should still remain the same in both sets of trace logs. We also use the handshaking mechanism as described in the Verification section of the Ibex manual to perform run-time checking for these kinds of tests.

Hope this helps!

**Comment by kabylkas** [comment]
Thank you!
