### ISSUE TITLE
debug_req + wfi

### ISSUE THREAD

**Issue by gautschimi** [lowRISC/ibex#991]
I'm not sure it is an issue. my testcase is the following:
1. ibex computes something and then needs to wait for an interrupt
2. ibex executes wfi to sleep
3. debugger access the core (wakes it up and reads some gpr)
4. debugger resumes (dret)
5. ibex continues with the instruction **after** the wfi (even though no interrupt has arrived yet)

It is probably the right behaviour but messes my test up. is there a way to tell ibex to reexecute the wfi upon return from debug mode?

I guess I could modify the PC in that case (maybe even gdb is taking care of that?)

**Comment by GregAC** [comment]
Closing this now, if there's any further comments feel free to make them or open a new issue.
